/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.cromatografia;

//import Classes.DAO.AnaliseCromatografoDAO;
//import Classes.DAO.AnaliseDAO;
//import Frm.Login.FrmSalvar;
//import Classes.Modelo.Analise;
//import Classes.Modelo.Cromatografo;
//import Classes.Modelo.Lote;
//import Classes.Modelo.Usuario;
//import Classes.Util.DataHora;
//import Frm.Recepcao.FrmProcurarLote;
//import Classes.Modelo.AnaliseCromatografo;
//import Classes.Modelo.Campanha;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael.lopes
 */
public class FrmLogAnalisePorLote extends javax.swing.JDialog {

    private static String system_name;
    private static int campanha_id;
    private List lotes;

    /**
     * Creates new form FrmNovoRegistroCromatografo
     *
     * @param parent
     * @param modal
     */
    public FrmLogAnalisePorLote(java.awt.Frame parent, boolean modal,
            String system, int campanha, List lote) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Análise de Amostras");
        system_name = system;
        campanha_id = campanha;
        lotes = lote;
        readAnalises();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDados = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnAdicionarLote = new javax.swing.JButton();
        btnRemoverLote = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAnalises = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Amostra"));

        btnAdicionarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAdicionarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarLoteActionPerformed(evt);
            }
        });

        btnRemoverLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnRemoverLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverLoteActionPerformed(evt);
            }
        });

        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Lote", "Método", "Retrabalho", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLotes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblLotes.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tblLotes);
        if (tblLotes.getColumnModel().getColumnCount() > 0) {
            tblLotes.getColumnModel().getColumn(0).setMinWidth(0);
            tblLotes.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblLotes.getColumnModel().getColumn(0).setMaxWidth(0);
            tblLotes.getColumnModel().getColumn(1).setMinWidth(100);
            tblLotes.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblLotes.getColumnModel().getColumn(2).setMinWidth(100);
            tblLotes.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblLotes.getColumnModel().getColumn(3).setMinWidth(80);
            tblLotes.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblLotes.getColumnModel().getColumn(4).setMinWidth(300);
            tblLotes.getColumnModel().getColumn(4).setPreferredWidth(300);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoverLote, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarLote, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAdicionarLote, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoverLote, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Análises"));

        tblAnalises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Análise", "Check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAnalises.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblAnalises);
        if (tblAnalises.getColumnModel().getColumnCount() > 0) {
            tblAnalises.getColumnModel().getColumn(0).setMinWidth(0);
            tblAnalises.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblAnalises.getColumnModel().getColumn(0).setMaxWidth(0);
            tblAnalises.getColumnModel().getColumn(2).setMinWidth(50);
            tblAnalises.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblAnalises.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addGap(0, 722, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        getContentPane().add(pnlDados);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
//        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//        int rowsAnalises = tblAnalises.getRowCount();
//        int rowsLotes = tblLotes.getRowCount();
//        try {
//            int analises = 0;
//            for (int row = 0; row < rowsAnalises; row++) {
//                if (tblAnalises.getValueAt(row, 2) != null) {
//                    if ((Boolean) tblAnalises.getValueAt(row, 2)) {
//                        analises++;
//                    }
//                }
//            }
//            if (tblLotes.getRowCount() <= 0) {
//                JOptionPane.showMessageDialog(null, "Selecione os Lotes!");
//                tblLotes.requestFocus();
//            } else if (analises == 0) {
//                JOptionPane.showMessageDialog(null, "Nenhuma Análise Selecionada!");
//                tblAnalises.requestFocus();
//            } else {
//                //Abre Dialog para savar
//                FrmSalvar frmSalvar = new FrmSalvar(null, true);
//                frmSalvar.setVisible(true);
//                if (FrmSalvar.senha()) {
//                    for (int rowLotes = 0; rowLotes < rowsLotes; rowLotes++) {
//                        for (int rowAnalises = 0; rowAnalises < rowsAnalises; rowAnalises++) {
//                            if (tblAnalises.getValueAt(rowAnalises, 2) != null) {
//                                if ((Boolean) tblAnalises.getValueAt(rowAnalises, 2)) {
//                                    criarAnalise((Integer) tblAnalises.getValueAt(rowAnalises, 0),
//                                            (Integer) tblLotes.getValueAt(rowLotes, 0),
//                                            (Boolean) tblLotes.getValueAt(rowLotes, 3),
//                                            tblLotes.getValueAt(rowLotes, 4).toString()
//                                    );
//                                }
//                            }
//                        }
//                        Lote lote = new Lote();
//                        lote.setLote_produto(tblLotes.getValueAt(rowLotes, 1).toString());
//                        lotes.add(lote);
//                    }
//                    dispose();
//                }
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Não foi possivel salvar. Algum Campo está inválido!");
//        }
//        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAdicionarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarLoteActionPerformed
//        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//        List<Lote> prds = new ArrayList<>();
//        FrmProcurarLote frm = new FrmProcurarLote(null, true, prds);
//        frm.setVisible(true);
//        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
//        DefaultTableModel model = (DefaultTableModel) tblLotes.getModel();
//        for (Lote lot : prds) {
//            model.addRow(new Object[]{
//                lot.getLote_id(),
//                lot.getLote_produto(),
//                lot.getMetodo().getCod_metodo(),
//                false,
//                ""
//            });
//        }
    }//GEN-LAST:event_btnAdicionarLoteActionPerformed

    private void btnRemoverLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverLoteActionPerformed
        if (tblLotes.getSelectedRow() != -1) {
            DefaultTableModel model = (DefaultTableModel) tblLotes.getModel();
            model.removeRow(tblLotes.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoverLoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogAnalisePorLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogAnalisePorLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogAnalisePorLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogAnalisePorLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLogAnalisePorLote dialog = new FrmLogAnalisePorLote(new javax.swing.JFrame(), true, null, 0, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarLote;
    public static javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRemoverLote;
    public static javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JTable tblAnalises;
    private javax.swing.JTable tblLotes;
    // End of variables declaration//GEN-END:variables

    private void readAnalises() {
//        DefaultTableModel model = (DefaultTableModel) tblAnalises.getModel();
//        AnaliseDAO anlsDao = new AnaliseDAO();
//        model.setNumRows(0);
//        for (Analise anls : anlsDao.readAnalise()) {
//            model.addRow(new Object[]{
//                anls.getAnalise_id(),
//                anls.getAnalise()
//            });
//        }
    }

    private void criarAnalise(int anls_id, int lote_id, boolean reanalise, String obs) {
//        try {
//            AnaliseCromatografo anlscro = new AnaliseCromatografo();
//            AnaliseCromatografoDAO anlscroDAO = new AnaliseCromatografoDAO();
//            Usuario user_registro = new Usuario();
//            Usuario user_inicio = new Usuario();
//            Lote lote = new Lote();
//            Cromatografo equip = new Cromatografo();
//            Analise anls = new Analise();
//            Campanha camp = new Campanha();
//            camp.setLog_campanha_id(campanha_id);
//            anlscro.setCampanha(camp);
//            anls.setAnalise_id(anls_id);
//            anlscro.setAnalise(anls);
//            lote.setLote_id(lote_id);
//            anlscro.setLote(lote);
//            equip.setSystem_name(system_name);
//            anlscro.setCromatografo(equip);
//            anlscro.setData_hora_inicio(DataHora.getTimestampDate(new Date()));
//            user_inicio.setUser(System.getProperty("user"));
//            anlscro.setUser_inicio(user_inicio);
//            anlscro.setData_hora_registro(DataHora.getTimestampDate(new Date()));
//            user_registro.setUser(System.getProperty("user"));
//            anlscro.setUser_registro(user_registro);
//            anlscro.setStatus("Em Análise");
//            anlscro.setObs(obs == null ? "" : obs);
//            anlscro.setRetrabalho_lote(reanalise);
//            anlscroDAO.createAnaliseCromatografo(anlscro);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
//        }
    }
}
