/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.cromatografia;

//import Frm.Login.FrmSalvarDataHora;
//import Classes.DAO.AnaliseCromatografoDAO;
//import Classes.DAO.AnaliseDAO;
//import Classes.DAO.CampanhaDAO;
//import Classes.DAO.ColunaDAO;
//import Classes.DAO.CromatografoDAO;
//import Classes.DAO.FaseMovelDAO;
//import Classes.DAO.SystemSuitabilityDAO;
//import Classes.Modelo.Analise;
//import Classes.Modelo.AnaliseCromatografo;
//import Classes.Modelo.Campanha;
//import Classes.Modelo.Coluna;
//import Classes.Modelo.Cromatografo;
//import Classes.Modelo.FaseMovel;
//import Classes.Modelo.SystemSuitability;
//import Classes.Modelo.Usuario;
//import Classes.Util.ComboBox;
//import Classes.Util.DataHora;
import java.awt.Cursor;
import java.sql.Timestamp;
import java.util.Date;
import java.util.TreeMap;
import javax.swing.JOptionPane;

/**
 *
 * @author rafael.lopes
 */
public class FrmNovoRegistro extends javax.swing.JDialog {

    private TreeMap<Integer, String> categoryMapAnaliseStatus = new TreeMap<>();
    private static String sys_name;
    private static Long campanha_id;
    private static int verificar_analise = 0;
    //private Timestamp data_inicio;

    /**
     * Creates new form FrmNovoRegistro
     *
     * @param parent
     * @param modal
     * @param system_name
     *
     */
    public FrmNovoRegistro(java.awt.Frame parent, boolean modal,
            String system_name, Long campanha, int analise) {
        super(parent, modal);
        initComponents();
        sys_name = system_name;
        campanha_id = campanha;
        verificar_analise = analise;
        setLocationRelativeTo(null);
        setTitle("Novo Registro");
        this.setResizable(false);
        readAnaliseStatus();
        carregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAnalise = new javax.swing.JButton();
        btnAjusteSistema = new javax.swing.JButton();
        btnAguardando = new javax.swing.JButton();
        btnEstabilizacao = new javax.swing.JButton();
        btnLimpeza = new javax.swing.JButton();
        btnManutencao = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNovaAnalise = new javax.swing.JButton();
        btnFimAnalise = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnFaseMovel = new javax.swing.JButton();
        btnColuna = new javax.swing.JButton();
        btnSystemSuitability = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnPassagemTurno = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnOutro = new javax.swing.JButton();
        cmbAnaliseStatus = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        btnAtividadesEquipamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        btnAnalise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnalise.setText("Análise");
        btnAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnaliseActionPerformed(evt);
            }
        });

        btnAjusteSistema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAjusteSistema.setText("Ajuste do Sistema");
        btnAjusteSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjusteSistemaActionPerformed(evt);
            }
        });

        btnAguardando.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAguardando.setText("Aguardando");
        btnAguardando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAguardandoActionPerformed(evt);
            }
        });

        btnEstabilizacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEstabilizacao.setText("Estabilização");
        btnEstabilizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstabilizacaoActionPerformed(evt);
            }
        });

        btnLimpeza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpeza.setText("Limpeza");
        btnLimpeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpezaActionPerformed(evt);
            }
        });

        btnManutencao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnManutencao.setText("Manutenção");
        btnManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManutencaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManutencao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpeza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstabilizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAguardando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjusteSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(btnAnalise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAjusteSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAguardando, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstabilizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpeza, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Início / Fim"));

        btnNovaAnalise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovaAnalise.setText("Nova Análise");
        btnNovaAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaAnaliseActionPerformed(evt);
            }
        });

        btnFimAnalise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFimAnalise.setText("Fim Análise");
        btnFimAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFimAnaliseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnNovaAnalise, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnFimAnalise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovaAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFimAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema"));

        btnFaseMovel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFaseMovel.setText("Fase Móvel");
        btnFaseMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaseMovelActionPerformed(evt);
            }
        });

        btnColuna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnColuna.setText("Coluna");
        btnColuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColunaActionPerformed(evt);
            }
        });

        btnSystemSuitability.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSystemSuitability.setText("System Suitability");
        btnSystemSuitability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemSuitabilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFaseMovel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnColuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSystemSuitability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFaseMovel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSystemSuitability, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Troca de Turno"));

        btnPassagemTurno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPassagemTurno.setText("Passagem de Turno");
        btnPassagemTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassagemTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPassagemTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPassagemTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Outro"));

        btnOutro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOutro.setText("Outro");
        btnOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroActionPerformed(evt);
            }
        });

        cmbAnaliseStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbAnaliseStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOutro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAnaliseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOutro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Atividades"));

        btnAtividadesEquipamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtividadesEquipamento.setText("Atividades");
        btnAtividadesEquipamento.setEnabled(false);
        btnAtividadesEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtividadesEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtividadesEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtividadesEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstabilizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstabilizacaoActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        novoRegistro(8, "EQUIPAMENTO");
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnEstabilizacaoActionPerformed

    private void btnAjusteSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjusteSistemaActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        novoRegistro(6, "EQUIPAMENTO");
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnAjusteSistemaActionPerformed

    private void btnAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnaliseActionPerformed
        if (verificar_analise == 1) {
            JOptionPane.showMessageDialog(null, "Coluna Cromatográfica não selecionada");
        } else if (verificar_analise == 3) {
            JOptionPane.showMessageDialog(null, "Sistema não está verificado");
        } else if (verificar_analise == 0) {
            novoRegistro(5, null);
        }
    }//GEN-LAST:event_btnAnaliseActionPerformed

    private void btnAguardandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAguardandoActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        novoRegistro(7, null);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnAguardandoActionPerformed

    private void btnLimpezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpezaActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        novoRegistro(9, "COLUNA");
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnLimpezaActionPerformed

    private void btnNovaAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaAnaliseActionPerformed
        FrmSelecionarCampanhaCromatografo frm = new FrmSelecionarCampanhaCromatografo(null, true, sys_name);
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNovaAnaliseActionPerformed

    private void btnFimAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFimAnaliseActionPerformed
//        int dialogResult = JOptionPane.showConfirmDialog(null,
//                "Deseja finalizar a Análise?", "Aviso", JOptionPane.YES_NO_OPTION);
//        if (dialogResult == 0) {
//            DataHora data_registro = new DataHora();
//            FrmSalvarDataHora frmSalvar = new FrmSalvarDataHora(null, true, sys_name, data_registro);
//            frmSalvar.setVisible(true);
//            Timestamp data_inicio = data_registro.getTimestampdatahora() == null
//                    ? DataHora.getTimestampDate(new Date())
//                    : data_registro.getTimestampdatahora();
//            if (frmSalvar.senha()) {
//                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                finalizarCampanha(data_inicio);
//                finalizarLotes();
//                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
//                dispose();
//            }
//        }
    }//GEN-LAST:event_btnFimAnaliseActionPerformed

    private void btnManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManutencaoActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        novoRegistro(10, "EQUIPAMENTO");
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnManutencaoActionPerformed

    private void btnOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroActionPerformed
//        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//        if (!cmbAnaliseStatus.getSelectedItem().toString().equals("")) {
//            if (cmbAnaliseStatus.getSelectedItem().toString().equals("START")) {
//                FrmFaseMovelStart frmFaseMovelStart = new FrmFaseMovelStart(null, true, sys_name);
//                frmFaseMovelStart.setVisible(true);
//                novoRegistro(ComboBox.getKeyForValue(cmbAnaliseStatus.getSelectedItem().toString(),
//                        categoryMapAnaliseStatus), "EQUIPAMENTO");
//            } else {
//                novoRegistro(ComboBox.getKeyForValue(cmbAnaliseStatus.getSelectedItem().toString(),
//                        categoryMapAnaliseStatus), null);
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Status da Análise inválida");
//            cmbAnaliseStatus.requestFocus();
//        }
//        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnOutroActionPerformed

    private void btnFaseMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaseMovelActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FrmFaseMovelCromatografo frmLogFM = new FrmFaseMovelCromatografo(null, true, sys_name, campanha_id);
        frmLogFM.setVisible(true);
        dispose();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnFaseMovelActionPerformed

    private void btnColunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColunaActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //FrmColunaCromatografo frmCol = new FrmColunaCromatografo(null, true, sys_name, campanha_id);
        //frmCol.setVisible(true);
        dispose();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnColunaActionPerformed

    private void btnSystemSuitabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemSuitabilityActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //FrmSystemCromatografo frmSystem = new FrmSystemCromatografo(null, true, sys_name, campanha_id);
        //frmSystem.setVisible(true);
        dispose();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnSystemSuitabilityActionPerformed

    private void btnPassagemTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassagemTurnoActionPerformed
//        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//        FrmTrocaTurno frm = new FrmTrocaTurno(null, true,
//                sys_name, campanha_id,
//                null, 0, true, false);
//        frm.setVisible(true);
//        dispose();
//        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPassagemTurnoActionPerformed

    private void btnAtividadesEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtividadesEquipamentoActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FrmAtividadeEquipamento frm = new FrmAtividadeEquipamento(null, true);
        frm.setVisible(true);
        dispose();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnAtividadesEquipamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmNovoRegistro dialog = new FrmNovoRegistro(new javax.swing.JFrame(), true, null, null, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAguardando;
    private javax.swing.JButton btnAjusteSistema;
    private javax.swing.JButton btnAnalise;
    private javax.swing.JButton btnAtividadesEquipamento;
    private javax.swing.JButton btnColuna;
    private javax.swing.JButton btnEstabilizacao;
    private javax.swing.JButton btnFaseMovel;
    private javax.swing.JButton btnFimAnalise;
    private javax.swing.JButton btnLimpeza;
    private javax.swing.JButton btnManutencao;
    private javax.swing.JButton btnNovaAnalise;
    private javax.swing.JButton btnOutro;
    private javax.swing.JButton btnPassagemTurno;
    private javax.swing.JButton btnSystemSuitability;
    private javax.swing.JComboBox cmbAnaliseStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    public final void readAnaliseStatus() {
//        cmbAnaliseStatus.removeAllItems();
//        cmbAnaliseStatus.addItem("");
//        categoryMapAnaliseStatus.clear();
//        AnaliseDAO anseDao = new AnaliseDAO();
//        for (Analise anls : anseDao.readAnaliseStatus()) {
//            Integer id = anls.getAnalise_status_id();
//            String name = anls.getAnalise_status();
//            cmbAnaliseStatus.addItem(name);
//            categoryMapAnaliseStatus.put(id, name);
//        }
    }

    private void novoRegistro(Integer analise_status, String analise_tipo) {
//        //Abre Dialog para savar
//        FrmDialogSalvar frmSalvar = new FrmDialogSalvar(null, true, sys_name,
//                analise_status, analise_tipo, campanha_id);
//        frmSalvar.setVisible(true);
//        if (FrmDialogSalvar.senha()) {
//            dispose();
//        }
    }

    private void finalizarCampanha(Timestamp data) {
//        Campanha camp = new Campanha();
//        Cromatografo equip = new Cromatografo();
//        CampanhaDAO campDao = new CampanhaDAO();
//        Usuario user = new Usuario();
//        CromatografoDAO equipDAO = new CromatografoDAO();
//        FaseMovel fase = new FaseMovel();
//        Coluna col = new Coluna();
//        Analise anls = new Analise();
//        SystemSuitability system = new SystemSuitability();
//        FaseMovelDAO faseDAO = new FaseMovelDAO();
//        ColunaDAO colDAO = new ColunaDAO();
//        SystemSuitabilityDAO systemDAO = new SystemSuitabilityDAO();
//        //busca pelo nome do equipamento
//        camp.setLog_campanha_id(campanha_id);
//        equip.setCampanha(camp);
//        equip.setSystem_name(sys_name);
//        equipDAO.selectLogCromatografo(equip);
//        col.setCromatografo(equip);
//        fase.setCromatografo(equip);
//        system.setCromatografo(equip);
//        int idCol = colDAO.selectIDUltimaColunaBySystem(col);
//        if (idCol > 0) {
//            col.setLog_coluna_id(idCol);
//            col.setData_registro_log(DataHora.getTimestampDate(new Date()));
//            col.setData_fim_log(DataHora.getTimestampDate(new Date()));
//            colDAO.updateFimLogColuna(col);
//        }
//        int idFase = faseDAO.selectIDUltimaFaseMovelBySystem(fase);
//        if (idFase > 0) {
//            fase.setFase_movel_id(idFase);
//            fase.setData_registro(DataHora.getTimestampDate(new Date()));
//            fase.setData_fim(DataHora.getTimestampDate(new Date()));
//            faseDAO.updateFimLogFaseMovel(fase);
//        }
//        int idSystem = systemDAO.selectIDUltimoSystemSuitabilityBySystem(system);
//        if (idSystem > 0) {
//            system.setSystem_suitability_id(idSystem);
//            system.setData_registro(DataHora.getTimestampDate(new Date()));
//            system.setData_fim(DataHora.getTimestampDate(new Date()));
//            systemDAO.updateFimLogSystemSuitability(system);
//        }
//        fase.setCromatografo(equip);
//        faseDAO.selectUltimaFaseMovelBySystem(fase);
//        colDAO.selectUltimaColunaBySystem(col);
//        equip.setData_fim(data);
//        equip.setData_registro(DataHora.getTimestampDate(new Date()));
//        user.setUser(System.getProperty("user"));
//        equip.setUsuario(user);
//        //verifica se o registro é uma NOVA ANÁLISE
//        //set FaseMovel e Coluna
//        try {
//            if (equip.getAnalise().getAnalise_status_id() == 1
//                    || equip.getAnalise().getAnalise_status_id() == 2) {
//                fase.setFase_movel_id(0);
//                col.setColuna_id(0);
//            }
//        } catch (Exception e) {
//            fase.setFase_movel_id(0);
//            col.setColuna_id(0);
//        }
//        equip.setFasemovel(fase);
//        equip.setColuna(col);
//        //Atualiza no registro anterior
//        equipDAO.updateLogCromatografo(equip);
//        //Aualiza Campanha como Final da Analise
//        camp.setCromatografo(equip);
//        campDao.selectCampanhaBySystem(camp);
//        camp.setData_fim(data);
//        camp.setUser_fim(user);
//        camp.setCor("Preto");
//        //Grava dados no banco
//        campDao.updateFimCampanha(camp);
//        //Gera Final da Analise
//        fase.setFase_movel_id(0);
//        col.setColuna_id(0);
//        equip.setFasemovel(fase);
//        equip.setColuna(col);
//        anls.setAnalise_status_id(2);
//        equip.setAnalise(anls);
//        equip.setSystem_name(sys_name);
//        equip.setData_inicio(data);
//        equip.setDescricao("FINAL ANÁLISE" + (camp.getNome_campanha().isEmpty()
//                ? "" : " - " + camp.getNome_campanha()));
//        user.setUser(System.getProperty("user"));
//        equip.setUsuario(user);
//        equip.setMetodos("");
//        equip.setObs_log("FINAL DA ANÁLISE");
//        //Grava dados no banco
//        equipDAO.createLogFimCromatografo(equip);
    }

    private void finalizarLotes() {
//        Cromatografo equip = new Cromatografo();
//        CromatografoDAO equipDAO = new CromatografoDAO();
//        equip.setSystem_name(sys_name);
//        equipDAO.selectCromatografoByName(equip);
//        AnaliseCromatografoDAO anlscroDao = new AnaliseCromatografoDAO();
//        Usuario user = new Usuario();
//        try {
//            if (anlscroDao.readAnaliseCromatografoAivo(equip).size() > 0) {
//                int dialogResult = JOptionPane.showConfirmDialog(null,
//                        "Exitem lotes Em Análise! \nDeseja Finalizar todos os Lotes?",
//                        "Aviso", JOptionPane.YES_NO_OPTION);
//                if (dialogResult == 0) {
//                    for (AnaliseCromatografo anlscro : anlscroDao.readAnaliseCromatografoAivo(equip)) {
//                        user.setUser(System.getProperty("user"));
//                        anlscro.setLog_lote_id(anlscro.getLog_lote_id());
//                        anlscro.setStatus("Finalizado");
//                        anlscro.setData_hora_fim(DataHora.getTimestampDate(new Date()));
//                        anlscro.setData_hora_registro(DataHora.getTimestampDate(new Date()));
//                        anlscro.setUser_fim(user);
//                        anlscro.setUser_registro(user);
//                        anlscroDao.updateFimLote(anlscro);
//                    }
//                }
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao atualizar dados: " + e);
//        }
    }

    private void carregar() {
//        try {
//            Campanha camp = new Campanha();
//            Cromatografo equip = new Cromatografo();
//            CromatografoDAO equipDAO = new CromatografoDAO();
//            CampanhaDAO campDao = new CampanhaDAO();
//            equip.setSystem_name(sys_name);
//            camp.setCromatografo(equip);
//            campDao.selectCampanhaFimBySystem(camp);
//            equipDAO.selectLogCromatografo(equip);
//            if ((camp.getUser_fim().getUser() == null && camp.getUser_inicio().getUser() != null)) {
//                btnNovaAnalise.setEnabled(false);
//                btnAjusteSistema.setEnabled(true);
//                btnAnalise.setEnabled(true);
//                btnEstabilizacao.setEnabled(true);
//                cmbAnaliseStatus.setEnabled(true);
//                btnOutro.setEnabled(true);
//                btnFaseMovel.setEnabled(true);
//                btnColuna.setEnabled(true);
//                btnSystemSuitability.setEnabled(true);
//                btnAguardando.setEnabled(true);
//                btnLimpeza.setEnabled(true);
//                btnManutencao.setEnabled(true);
//                btnOutro.setEnabled(true);
//            } else if (camp.getUser_fim().getUser() != null) {
//                btnFimAnalise.setEnabled(false);
//                btnAjusteSistema.setEnabled(false);
//                btnAnalise.setEnabled(false);
//                btnEstabilizacao.setEnabled(false);
//                cmbAnaliseStatus.setEnabled(true);
//                btnOutro.setEnabled(true);
//                btnFaseMovel.setEnabled(false);
//                btnColuna.setEnabled(false);
//                btnSystemSuitability.setEnabled(false);
//                btnAguardando.setEnabled(true);
//                btnLimpeza.setEnabled(true);
//                btnManutencao.setEnabled(true);
//            }
//        } catch (Exception e) {
//            btnNovaAnalise.setEnabled(true);
//            btnFimAnalise.setEnabled(false);
//            btnAguardando.setEnabled(true);
//            btnAjusteSistema.setEnabled(false);
//            btnAnalise.setEnabled(false);
//            btnEstabilizacao.setEnabled(false);
//            btnLimpeza.setEnabled(true);
//            btnManutencao.setEnabled(true);
//            btnOutro.setEnabled(true);
//            cmbAnaliseStatus.setEnabled(true);
//            btnFaseMovel.setEnabled(false);
//            btnColuna.setEnabled(false);
//            btnSystemSuitability.setEnabled(false);
//        }
    }

}
