/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.cromatografia;

//import Classes.DAO.CromatografoDAO;
//import Classes.DAO.SystemSuitabilityDAO;
//import Classes.Modelo.Cromatografo;
//import Classes.Modelo.SystemSuitability;
//import Classes.Modelo.Usuario;
//import Classes.Util.DataHora;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rafael.lopes
 */
public class FrmVerificarSystemCromatografo extends javax.swing.JDialog {

    private static int sys_id;
    private static String sys_name;
    private static int campanha_id;

    /**
     * Creates new form FrmNovoRegistroCromatografo
     *
     * @param parent
     * @param modal
     * @param system_name
     */
    public FrmVerificarSystemCromatografo(java.awt.Frame parent, boolean modal, int system_id,
            String system_name, int campanha) {
        super(parent, modal);
        initComponents();
//        setResizable(false);
//        setLocationRelativeTo(null);
//        setTitle("Verificação de Systema");
//        sys_id = system_id;
//        sys_name = system_name;
//        campanha_id = campanha;
//        loadSolucao();
    }
    
    public FrmVerificarSystemCromatografo(java.awt.Frame parent, boolean modal, int system_id) {
        super(parent, modal);
        initComponents();
//        setResizable(false);
//        setLocationRelativeTo(null);
//        setTitle("Verificação de Systema");
//        sys_id = system_id;
//        loadSolucao();
//        btnSalvar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDados = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtDescricaoSolucao1 = new javax.swing.JTextField();
        txtUserSolucao1 = new javax.swing.JTextField();
        txtDescricaoSolucao2 = new javax.swing.JTextField();
        txtUserSolucao2 = new javax.swing.JTextField();
        txtDescricaoSolucao3 = new javax.swing.JTextField();
        txtUserSolucao3 = new javax.swing.JTextField();
        txtDescricaoSolucao4 = new javax.swing.JTextField();
        txtUserSolucao4 = new javax.swing.JTextField();
        txtDescricaoSolucao5 = new javax.swing.JTextField();
        txtUserSolucao5 = new javax.swing.JTextField();
        txtDescricaoSolucao6 = new javax.swing.JTextField();
        txtUserSolucao6 = new javax.swing.JTextField();
        txtDescricaoSolucao7 = new javax.swing.JTextField();
        txtUserSolucao7 = new javax.swing.JTextField();
        txtDescricaoSolucao8 = new javax.swing.JTextField();
        txtUserSolucao8 = new javax.swing.JTextField();
        txtDescricaoSolucao9 = new javax.swing.JTextField();
        txtUserSolucao9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSolucao1 = new javax.swing.JTextField();
        txtSolucao2 = new javax.swing.JTextField();
        txtSolucao3 = new javax.swing.JTextField();
        txtSolucao4 = new javax.swing.JTextField();
        txtSolucao5 = new javax.swing.JTextField();
        txtSolucao6 = new javax.swing.JTextField();
        txtSolucao7 = new javax.swing.JTextField();
        txtSolucao8 = new javax.swing.JTextField();
        txtSolucao9 = new javax.swing.JTextField();
        txtDataSolucao1 = new javax.swing.JTextField();
        txtDataSolucao2 = new javax.swing.JTextField();
        txtDataSolucao3 = new javax.swing.JTextField();
        txtDataSolucao4 = new javax.swing.JTextField();
        txtDataSolucao5 = new javax.swing.JTextField();
        txtDataSolucao6 = new javax.swing.JTextField();
        txtDataSolucao7 = new javax.swing.JTextField();
        txtDataSolucao8 = new javax.swing.JTextField();
        txtDataSolucao9 = new javax.swing.JTextField();
        txtNumeroSolucao1 = new javax.swing.JTextField();
        txtNumeroSolucao9 = new javax.swing.JTextField();
        txtNumeroSolucao8 = new javax.swing.JTextField();
        txtNumeroSolucao7 = new javax.swing.JTextField();
        txtNumeroSolucao6 = new javax.swing.JTextField();
        txtNumeroSolucao2 = new javax.swing.JTextField();
        txtNumeroSolucao3 = new javax.swing.JTextField();
        txtNumeroSolucao4 = new javax.swing.JTextField();
        txtNumeroSolucao5 = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Metodologia"));

        txtDescricaoSolucao1.setEditable(false);
        txtDescricaoSolucao1.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricaoSolucao1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao1.setEditable(false);
        txtUserSolucao1.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDescricaoSolucao2.setEditable(false);
        txtDescricaoSolucao2.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricaoSolucao2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao2.setEditable(false);
        txtUserSolucao2.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDescricaoSolucao3.setEditable(false);
        txtDescricaoSolucao3.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricaoSolucao3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao3.setEditable(false);
        txtUserSolucao3.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDescricaoSolucao4.setEditable(false);
        txtDescricaoSolucao4.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricaoSolucao4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao4.setEditable(false);
        txtUserSolucao4.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDescricaoSolucao5.setEditable(false);
        txtDescricaoSolucao5.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricaoSolucao5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao5.setEditable(false);
        txtUserSolucao5.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDescricaoSolucao6.setEditable(false);
        txtDescricaoSolucao6.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricaoSolucao6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao6.setEditable(false);
        txtUserSolucao6.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDescricaoSolucao7.setEditable(false);
        txtDescricaoSolucao7.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricaoSolucao7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao7.setEditable(false);
        txtUserSolucao7.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDescricaoSolucao8.setEditable(false);
        txtDescricaoSolucao8.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricaoSolucao8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao8.setEditable(false);
        txtUserSolucao8.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDescricaoSolucao9.setEditable(false);
        txtDescricaoSolucao9.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricaoSolucao9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao9.setEditable(false);
        txtUserSolucao9.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Solução");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nº");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Descrição");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Fabricação");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Responsável");

        txtSolucao1.setEditable(false);
        txtSolucao1.setBackground(new java.awt.Color(204, 204, 204));

        txtSolucao2.setEditable(false);
        txtSolucao2.setBackground(new java.awt.Color(204, 204, 204));

        txtSolucao3.setEditable(false);
        txtSolucao3.setBackground(new java.awt.Color(204, 204, 204));

        txtSolucao4.setEditable(false);
        txtSolucao4.setBackground(new java.awt.Color(204, 204, 204));

        txtSolucao5.setEditable(false);
        txtSolucao5.setBackground(new java.awt.Color(204, 204, 204));

        txtSolucao6.setEditable(false);
        txtSolucao6.setBackground(new java.awt.Color(204, 204, 204));

        txtSolucao7.setEditable(false);
        txtSolucao7.setBackground(new java.awt.Color(204, 204, 204));

        txtSolucao8.setEditable(false);
        txtSolucao8.setBackground(new java.awt.Color(204, 204, 204));

        txtSolucao9.setEditable(false);
        txtSolucao9.setBackground(new java.awt.Color(204, 204, 204));

        txtDataSolucao1.setEditable(false);
        txtDataSolucao1.setBackground(new java.awt.Color(204, 204, 204));
        txtDataSolucao1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDataSolucao2.setEditable(false);
        txtDataSolucao2.setBackground(new java.awt.Color(204, 204, 204));
        txtDataSolucao2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDataSolucao3.setEditable(false);
        txtDataSolucao3.setBackground(new java.awt.Color(204, 204, 204));
        txtDataSolucao3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDataSolucao4.setEditable(false);
        txtDataSolucao4.setBackground(new java.awt.Color(204, 204, 204));
        txtDataSolucao4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDataSolucao5.setEditable(false);
        txtDataSolucao5.setBackground(new java.awt.Color(204, 204, 204));
        txtDataSolucao5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDataSolucao6.setEditable(false);
        txtDataSolucao6.setBackground(new java.awt.Color(204, 204, 204));
        txtDataSolucao6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDataSolucao7.setEditable(false);
        txtDataSolucao7.setBackground(new java.awt.Color(204, 204, 204));
        txtDataSolucao7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDataSolucao8.setEditable(false);
        txtDataSolucao8.setBackground(new java.awt.Color(204, 204, 204));
        txtDataSolucao8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDataSolucao9.setEditable(false);
        txtDataSolucao9.setBackground(new java.awt.Color(204, 204, 204));
        txtDataSolucao9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNumeroSolucao1.setEditable(false);
        txtNumeroSolucao1.setBackground(new java.awt.Color(204, 204, 204));

        txtNumeroSolucao9.setEditable(false);
        txtNumeroSolucao9.setBackground(new java.awt.Color(204, 204, 204));

        txtNumeroSolucao8.setEditable(false);
        txtNumeroSolucao8.setBackground(new java.awt.Color(204, 204, 204));

        txtNumeroSolucao7.setEditable(false);
        txtNumeroSolucao7.setBackground(new java.awt.Color(204, 204, 204));

        txtNumeroSolucao6.setEditable(false);
        txtNumeroSolucao6.setBackground(new java.awt.Color(204, 204, 204));

        txtNumeroSolucao2.setEditable(false);
        txtNumeroSolucao2.setBackground(new java.awt.Color(204, 204, 204));

        txtNumeroSolucao3.setEditable(false);
        txtNumeroSolucao3.setBackground(new java.awt.Color(204, 204, 204));

        txtNumeroSolucao4.setEditable(false);
        txtNumeroSolucao4.setBackground(new java.awt.Color(204, 204, 204));

        txtNumeroSolucao5.setEditable(false);
        txtNumeroSolucao5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumeroSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataSolucao4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumeroSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataSolucao5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumeroSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataSolucao6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumeroSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataSolucao7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumeroSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataSolucao8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumeroSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataSolucao3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataSolucao2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSolucao1)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroSolucao1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtDescricaoSolucao1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDataSolucao1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUserSolucao1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescricaoSolucao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroSolucao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserSolucao1)
                            .addComponent(txtDataSolucao1)))
                    .addComponent(txtSolucao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescricaoSolucao2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescricaoSolucao3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescricaoSolucao4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescricaoSolucao5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescricaoSolucao6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescricaoSolucao7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescricaoSolucao8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescricaoSolucao9)
                            .addComponent(txtDataSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtUserSolucao9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Validar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlDados);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        updateSystemSuitability();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVerificarSystemCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVerificarSystemCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVerificarSystemCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVerificarSystemCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmVerificarSystemCromatografo dialog = new FrmVerificarSystemCromatografo(new javax.swing.JFrame(), true, 0, null, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JTextField txtDataSolucao1;
    private javax.swing.JTextField txtDataSolucao2;
    private javax.swing.JTextField txtDataSolucao3;
    private javax.swing.JTextField txtDataSolucao4;
    private javax.swing.JTextField txtDataSolucao5;
    private javax.swing.JTextField txtDataSolucao6;
    private javax.swing.JTextField txtDataSolucao7;
    private javax.swing.JTextField txtDataSolucao8;
    private javax.swing.JTextField txtDataSolucao9;
    private javax.swing.JTextField txtDescricaoSolucao1;
    private javax.swing.JTextField txtDescricaoSolucao2;
    private javax.swing.JTextField txtDescricaoSolucao3;
    private javax.swing.JTextField txtDescricaoSolucao4;
    private javax.swing.JTextField txtDescricaoSolucao5;
    private javax.swing.JTextField txtDescricaoSolucao6;
    private javax.swing.JTextField txtDescricaoSolucao7;
    private javax.swing.JTextField txtDescricaoSolucao8;
    private javax.swing.JTextField txtDescricaoSolucao9;
    private javax.swing.JTextField txtNumeroSolucao1;
    private javax.swing.JTextField txtNumeroSolucao2;
    private javax.swing.JTextField txtNumeroSolucao3;
    private javax.swing.JTextField txtNumeroSolucao4;
    private javax.swing.JTextField txtNumeroSolucao5;
    private javax.swing.JTextField txtNumeroSolucao6;
    private javax.swing.JTextField txtNumeroSolucao7;
    private javax.swing.JTextField txtNumeroSolucao8;
    private javax.swing.JTextField txtNumeroSolucao9;
    private javax.swing.JTextField txtSolucao1;
    private javax.swing.JTextField txtSolucao2;
    private javax.swing.JTextField txtSolucao3;
    private javax.swing.JTextField txtSolucao4;
    private javax.swing.JTextField txtSolucao5;
    private javax.swing.JTextField txtSolucao6;
    private javax.swing.JTextField txtSolucao7;
    private javax.swing.JTextField txtSolucao8;
    private javax.swing.JTextField txtSolucao9;
    private javax.swing.JTextField txtUserSolucao1;
    private javax.swing.JTextField txtUserSolucao2;
    private javax.swing.JTextField txtUserSolucao3;
    private javax.swing.JTextField txtUserSolucao4;
    private javax.swing.JTextField txtUserSolucao5;
    private javax.swing.JTextField txtUserSolucao6;
    private javax.swing.JTextField txtUserSolucao7;
    private javax.swing.JTextField txtUserSolucao8;
    private javax.swing.JTextField txtUserSolucao9;
    // End of variables declaration//GEN-END:variables

    private void loadSolucao() {
//        SystemSuitability system = new SystemSuitability();
//        SystemSuitabilityDAO systemDAO = new SystemSuitabilityDAO();
//        system.setSystem_suitability_id(sys_id);
//        systemDAO.selectSystemSuitability(system);
//
//        txtSolucao1.setText(system.getSolucao_1());
//        txtSolucao2.setText(system.getSolucao_2());
//        txtSolucao3.setText(system.getSolucao_3());
//        txtSolucao4.setText(system.getSolucao_4());
//        txtSolucao5.setText(system.getSolucao_5());
//        txtSolucao6.setText(system.getSolucao_6());
//        txtSolucao7.setText(system.getSolucao_7());
//        txtSolucao8.setText(system.getSolucao_8());
//        txtSolucao9.setText(system.getSolucao_9());
//
//        txtNumeroSolucao1.setText(String.valueOf(system.getNumero_solucao_1() == 0 ? "" : system.getNumero_solucao_1()));
//        txtNumeroSolucao2.setText(String.valueOf(system.getNumero_solucao_2() == 0 ? "" : system.getNumero_solucao_2()));
//        txtNumeroSolucao3.setText(String.valueOf(system.getNumero_solucao_3() == 0 ? "" : system.getNumero_solucao_3()));
//        txtNumeroSolucao4.setText(String.valueOf(system.getNumero_solucao_4() == 0 ? "" : system.getNumero_solucao_4()));
//        txtNumeroSolucao5.setText(String.valueOf(system.getNumero_solucao_5() == 0 ? "" : system.getNumero_solucao_5()));
//        txtNumeroSolucao6.setText(String.valueOf(system.getNumero_solucao_6() == 0 ? "" : system.getNumero_solucao_6()));
//        txtNumeroSolucao7.setText(String.valueOf(system.getNumero_solucao_7() == 0 ? "" : system.getNumero_solucao_7()));
//        txtNumeroSolucao8.setText(String.valueOf(system.getNumero_solucao_8() == 0 ? "" : system.getNumero_solucao_8()));
//        txtNumeroSolucao9.setText(String.valueOf(system.getNumero_solucao_9() == 0 ? "" : system.getNumero_solucao_9()));
//
//        txtDescricaoSolucao1.setText(system.getDescricao_solucao_1());
//        txtDescricaoSolucao2.setText(system.getDescricao_solucao_2());
//        txtDescricaoSolucao3.setText(system.getDescricao_solucao_3());
//        txtDescricaoSolucao4.setText(system.getDescricao_solucao_4());
//        txtDescricaoSolucao5.setText(system.getDescricao_solucao_5());
//        txtDescricaoSolucao6.setText(system.getDescricao_solucao_6());
//        txtDescricaoSolucao7.setText(system.getDescricao_solucao_7());
//        txtDescricaoSolucao8.setText(system.getDescricao_solucao_8());
//        txtDescricaoSolucao9.setText(system.getDescricao_solucao_9());
//
//        txtDataSolucao1.setText(DataHora.getStringDate(system.getData_solucao_1()));
//        txtDataSolucao2.setText(DataHora.getStringDate(system.getData_solucao_2()));
//        txtDataSolucao3.setText(DataHora.getStringDate(system.getData_solucao_3()));
//        txtDataSolucao4.setText(DataHora.getStringDate(system.getData_solucao_4()));
//        txtDataSolucao5.setText(DataHora.getStringDate(system.getData_solucao_5()));
//        txtDataSolucao6.setText(DataHora.getStringDate(system.getData_solucao_6()));
//        txtDataSolucao7.setText(DataHora.getStringDate(system.getData_solucao_7()));
//        txtDataSolucao8.setText(DataHora.getStringDate(system.getData_solucao_8()));
//        txtDataSolucao9.setText(DataHora.getStringDate(system.getData_solucao_9()));
//
//        txtUserSolucao1.setText(system.getUser_solucao_1().getUser());
//        txtUserSolucao2.setText(system.getUser_solucao_2().getUser());
//        txtUserSolucao3.setText(system.getUser_solucao_3().getUser());
//        txtUserSolucao4.setText(system.getUser_solucao_4().getUser());
//        txtUserSolucao5.setText(system.getUser_solucao_5().getUser());
//        txtUserSolucao6.setText(system.getUser_solucao_6().getUser());
//        txtUserSolucao7.setText(system.getUser_solucao_7().getUser());
//        txtUserSolucao8.setText(system.getUser_solucao_8().getUser());
//        txtUserSolucao9.setText(system.getUser_solucao_9().getUser());
    }

    private void updateSystemSuitability() {
//        SystemSuitability system = new SystemSuitability();
//        SystemSuitabilityDAO systemDAO = new SystemSuitabilityDAO();
//        Usuario user = new Usuario();
//        try {
//            Integer analise_status = 15;
//            //Seleciona o Equipamento
//            Cromatografo equip = new Cromatografo();
//            CromatografoDAO equipDAO = new CromatografoDAO();
//            equip.setSystem_name(sys_name);
//            equipDAO.selectCromatografoByName(equip);
//            //Abre Dialog para savar
//            FrmDialogSalvar frmSalvar = new FrmDialogSalvar(null, true, sys_name,
//                    analise_status, "SYSTEM SUITABILITY", campanha_id);
//            frmSalvar.setVisible(true);
//            if (FrmDialogSalvar.senha()) {
//                system.setSystem_suitability_id(sys_id);
//                user.setUser(System.getProperty("user"));
//                system.setUser_check(user);
//                system.setData_registro(DataHora.getTimestampDate(new Date()));
//                system.setCheck_system_suitability(true);
//                systemDAO.updateValidarSystemSuitability(system);
//                dispose();
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao atualizar dados: " + e);
//        }
    }

}
