/*
 * Copyright (C) 2018 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.trocaturno;

import br.com.lablims.dao.GrupoDAO;
import br.com.lablims.dao.TrocaTurnoDAO;
import br.com.lablims.dao.TurnoDAO;
import br.com.lablims.dao.UsuarioDAO;
import br.com.lablims.model.Grupo;
import br.com.lablims.model.TrocaTurno;
import br.com.lablims.model.Turno;
import br.com.lablims.model.Usuario;
import br.com.lablims.util.ComboBox;
import br.com.lablims.util.DataHora;
import br.com.lablims.util.Frames;
import br.com.lablims.util.Senha;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.TreeMap;
import javax.swing.SwingWorker;

/**
 *
 * @author rafael.lopes
 */
public class FrmTrocaTurno extends javax.swing.JDialog {

    private TreeMap<Long, String> categoryMapTurno = new TreeMap<>();
    private boolean novoTrocaTurno = false;
    private boolean salvarTrocaTurno = false;
    private Long turno_id;
    private String user_name;
    private String agrupador;

    /**
     * Creates new form FrmTrocaTurno
     *
     * @param parent
     * @param modal
     * @param agrup
     */
    public FrmTrocaTurno(java.awt.Frame parent, boolean modal, String agrup) {
        super(parent, modal);
        initComponents();
        Frames.setUpFrame(this, "Troca de Turno", false);
        readTurno();
        agrupador = agrup;
        novoTrocaTurno = true;
    }
    
    public FrmTrocaTurno(java.awt.Frame parent, boolean modal, Long id, Boolean novo, Boolean salvar) {
        super(parent, modal);
        initComponents();
        Frames.setUpFrame(this, "Troca de Turno", false);
        agrupador = "Geral";
        novoTrocaTurno = novo;
        salvarTrocaTurno = salvar;
        turno_id = id;
        if (novo) {
            readTurno();
        } else {
            readTurno();
            carregarDados(id);
        }
    }

    public FrmTrocaTurno(java.awt.Frame parent, boolean modal, Long id, Boolean novo, Boolean salvar, String agrup) {
        super(parent, modal);
        initComponents();
        Frames.setUpFrame(this, "Troca de Turno", false);
        agrupador = agrup;
        novoTrocaTurno = novo;
        salvarTrocaTurno = salvar;
        turno_id = id;
        if (novo) {
            readTurno();
        } else {
            readTurno();
            carregarDados(id);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoTurno = new javax.swing.JTextArea();
        btnSalvarTurno = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbTurno = new javax.swing.JComboBox();
        btnImprimirRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Descrição");

        txtDescricaoTurno.setColumns(20);
        txtDescricaoTurno.setLineWrap(true);
        txtDescricaoTurno.setRows(5);
        txtDescricaoTurno.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescricaoTurno);

        btnSalvarTurno.setText("Salvar");
        btnSalvarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTurnoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Turno:");

        btnImprimirRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_print.png"))); // NOI18N
        btnImprimirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnImprimirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnImprimirRelatorio))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvarTurno))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTurnoActionPerformed
        Senha senha = new Senha();
        if (cmbTurno.getSelectedItem().toString().isEmpty() || cmbTurno.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Turno inválido");
            cmbTurno.requestFocus();
        } else if (txtDescricaoTurno.getText().isEmpty() || txtDescricaoTurno.getText() == null) {
            JOptionPane.showMessageDialog(null, "Descrição inválida");
            txtDescricaoTurno.requestFocus();
        } else if (novoTrocaTurno) {
            if (senha.Salvar()) {
                criarTrocaTurno();
            }
        } else {
            if (senha.Salvar()) {
                atulizarTrocaTurno();
            }
        }
    }//GEN-LAST:event_btnSalvarTurnoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnImprimirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRelatorioActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null,
                "Deseja Imprimir Relatorio de Troca de Turno ?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (dialogResult == 0) {
            MessageFormat header = createFormat("Turno : "  
                    + cmbTurno.getSelectedItem().toString() + " - " + user_name);
            MessageFormat footer = createFormat("Impresso por: " + System.getProperty("user") + "  -  "
                    + DataHora.getStringDateTime(new Date()) + "\n");
            boolean interactive = true;
            boolean background = true;

            PrintingTask task = new PrintingTask(header, footer, interactive);
            if (background) {
                task.execute();
            } else {
                task.run();
            }
        }
    }//GEN-LAST:event_btnImprimirRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrocaTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrocaTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrocaTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrocaTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmTrocaTurno dialog = new FrmTrocaTurno(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImprimirRelatorio;
    public static javax.swing.JButton btnSalvarTurno;
    private javax.swing.JComboBox cmbTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescricaoTurno;
    // End of variables declaration//GEN-END:variables

    private void carregarDados(Long id) {
        try {
            TrocaTurnoDAO turnoDao = new TrocaTurnoDAO();
            TrocaTurno turno = turnoDao.findById(TrocaTurno.class, id);
            txtDescricaoTurno.setText(turno.getPassagem());
            String[] tipo = {turno.getTurno().getTurno()};
            cmbTurno.setSelectedItem(tipo[0]);
            user_name = turno.getUsuario().getNome();
            if (turno.getUsuario().getUsuario().equals(System.getProperty("user"))) {
                if (salvarTrocaTurno) {
                    btnSalvarTurno.setVisible(true);
                } else {
                    btnSalvarTurno.setVisible(false);
                    cmbTurno.setEnabled(false);
                }
            } else {
                btnSalvarTurno.setVisible(false);
                cmbTurno.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
        }

    }

    private void readTurno() {
        cmbTurno.removeAllItems();
        cmbTurno.addItem("");
        categoryMapTurno.clear();
        TurnoDAO turnoDAO = new TurnoDAO();
        try {
            for (Turno turno : turnoDAO.findEntities(Turno.class)) {
                Long id = turno.getId();
                String name = turno.getTurno();
                cmbTurno.addItem(name);
                categoryMapTurno.put(id, name);
            }
        } catch (Exception e) {
        }
    }

    private void criarTrocaTurno() {
        TrocaTurno turno = new TrocaTurno();
        TrocaTurnoDAO turnoDAO = new TrocaTurnoDAO();
        try {
            Usuario usuario = new UsuarioDAO().findById(Usuario.class, Long.parseLong(System.getProperty("user_id")));
            turno.setUsuario(usuario);
            turno.setGrupo(new GrupoDAO().findById(Grupo.class, usuario.getGrupo().getId()));
            turno.setSetor(null);
            turno.setTurno(new TurnoDAO().findById(Turno.class, ComboBox.getKeyForValue(cmbTurno.getSelectedItem().toString(), categoryMapTurno)));
            turno.setPassagem(txtDescricaoTurno.getText());
            turno.setDataRegistro(new Date());
            turno.setAgrupador(agrupador);
            turnoDAO.salvar(turno);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
        } finally {
            dispose();
        }
    }

    private void atulizarTrocaTurno() {
        TrocaTurnoDAO turnoDAO = new TrocaTurnoDAO();
        try {
            TrocaTurno turno = turnoDAO.findById(TrocaTurno.class, turno_id);
            if (!cmbTurno.getSelectedItem().toString().equals(turno.getTurno().getTurno())) {
                turno.setTurno(new TurnoDAO().findById(Turno.class, ComboBox.getKeyForValue(cmbTurno.getSelectedItem().toString(), categoryMapTurno)));
            }
            turno.setPassagem(txtDescricaoTurno.getText());
            turno.setDataRegistro(DataHora.getTimestampDate(new Date()));
            turnoDAO.salvar(turno);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar dados: " + e);
        } finally {
            dispose();
        }
    }

    private class PrintingTask extends SwingWorker<Object, Object> {

        private final MessageFormat headerFormat;
        private final MessageFormat footerFormat;
        private final boolean interactive;
        private volatile boolean complete = false;
        private volatile String message;

        public PrintingTask(MessageFormat header, MessageFormat footer,
                boolean interactive) {
            this.headerFormat = header;
            this.footerFormat = footer;
            this.interactive = interactive;
        }

        @Override
        protected Object doInBackground() {
            try {
                complete = txtDescricaoTurno.print(headerFormat, footerFormat,
                        true, null, null, interactive);
                message = "Impressão " + (complete ? "Finalizada" : "Cancelada");
            } catch (PrinterException ex) {
                message = "Desculpe, ocorreu um erro na impressora";
            } catch (SecurityException ex) {
                message = "Desculpe, não foi possivel acessar a impressora por motivos de segurança";
            }
            return null;
        }

        @Override
        protected void done() {
            message(!complete, message);
        }
    }

    private MessageFormat createFormat(String texto) {
        if (texto != null && texto.length() > 0) {
            try {
                return new MessageFormat(texto);
            } catch (IllegalArgumentException e) {
                error("Desculpe, este formato é inválido.");
            }
        }
        return null;
    }

    private void message(boolean error, String msg) {
        int type = (error ? JOptionPane.ERROR_MESSAGE
                : JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(this, msg, "Imprimindo", type);
    }

    private void error(String msg) {
        message(true, msg);
    }

}
