/*
 * Copyright (C) 2019 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.registrosolucao;

import br.com.lablims.dao.RegistroSolucaoReagenteDAO;
import br.com.lablims.view.coluna.FrmImprimirRelatorio;
import br.com.lablims.model.RegistroSolucaoReagente;
import br.com.lablims.util.AcessoSistema;
import br.com.lablims.util.DataHora;
import br.com.lablims.util.Frames;
import br.com.lablims.util.Senha;
import br.com.lablims.util.TableSorter;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael.lopes
 */
public class FrmRegistroSolucaoReagente extends javax.swing.JFrame {

    private String ACESSO = new AcessoSistema().getAcessoSistema(this);

    /**
     * Creates new form NewJDialog
     */
    public FrmRegistroSolucaoReagente() {
        initComponents();
        Frames.setUpFrame(this, "Soluções Reagentes", false);
        read();
        btnNovo.setEnabled(AcessoSistema.criarDados(ACESSO));
        btnEditar.setEnabled(AcessoSistema.editarDados(ACESSO));
        btnExcluir.setEnabled(AcessoSistema.deletarDados(ACESSO));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblPaneMetodologia = new javax.swing.JTabbedPane();
        pnlColunas = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolucoes = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnExcluir = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnAtualizar = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnEtiqueta = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btnRelatorio = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btnDescarte = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        btnReativar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnDescarte1 = new javax.swing.JButton();
        pnlAuditTrail = new javax.swing.JPanel();
        pnlAuditoria = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAuditoria = new javax.swing.JTable();
        txtPesquisarAuditoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Soluções"));

        tblSolucoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Solução_Id", "Descrição", "Lote", "Quantidade", "Analista / Data", "Conferente / Data", "Versão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSolucoes.setSurrendersFocusOnKeystroke(true);
        tblSolucoes.getTableHeader().setReorderingAllowed(false);
        tblSolucoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSolucoesMouseClicked(evt);
            }
        });
        tblSolucoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSolucoesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblSolucoes);
        if (tblSolucoes.getColumnModel().getColumnCount() > 0) {
            tblSolucoes.getColumnModel().getColumn(0).setMinWidth(80);
            tblSolucoes.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblSolucoes.getColumnModel().getColumn(0).setMaxWidth(80);
            tblSolucoes.getColumnModel().getColumn(2).setMinWidth(120);
            tblSolucoes.getColumnModel().getColumn(2).setPreferredWidth(120);
            tblSolucoes.getColumnModel().getColumn(2).setMaxWidth(120);
            tblSolucoes.getColumnModel().getColumn(3).setMinWidth(100);
            tblSolucoes.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblSolucoes.getColumnModel().getColumn(3).setMaxWidth(100);
            tblSolucoes.getColumnModel().getColumn(6).setMinWidth(80);
            tblSolucoes.getColumnModel().getColumn(6).setPreferredWidth(80);
            tblSolucoes.getColumnModel().getColumn(6).setMaxWidth(80);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        jLabel4.setText("Pesquisar:");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);
        jToolBar1.add(jSeparator6);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);
        jToolBar1.add(jSeparator1);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_close.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setPreferredSize(new java.awt.Dimension(60, 60));
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluir);
        jToolBar1.add(jSeparator8);

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_atualizar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setFocusable(false);
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizar.setPreferredSize(new java.awt.Dimension(60, 60));
        btnAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAtualizar);
        jToolBar1.add(jSeparator9);

        btnEtiqueta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_barcode.png"))); // NOI18N
        btnEtiqueta.setText("Etiqueta");
        btnEtiqueta.setFocusable(false);
        btnEtiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEtiqueta.setPreferredSize(new java.awt.Dimension(60, 60));
        btnEtiqueta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtiquetaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEtiqueta);
        jToolBar1.add(jSeparator11);

        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_print.png"))); // NOI18N
        btnRelatorio.setText("Relatório");
        btnRelatorio.setFocusable(false);
        btnRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorio.setPreferredSize(new java.awt.Dimension(60, 60));
        btnRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRelatorio);
        jToolBar1.add(jSeparator10);

        btnDescarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_approval_32.png"))); // NOI18N
        btnDescarte.setText("Ativar");
        btnDescarte.setFocusable(false);
        btnDescarte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescarte.setPreferredSize(new java.awt.Dimension(60, 60));
        btnDescarte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDescarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescarteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDescarte);
        jToolBar1.add(jSeparator13);

        btnReativar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_close_window_32.png"))); // NOI18N
        btnReativar.setText("Desativar");
        btnReativar.setFocusable(false);
        btnReativar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReativar.setPreferredSize(new java.awt.Dimension(60, 60));
        btnReativar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReativarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReativar);
        jToolBar1.add(jSeparator2);

        btnDescarte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_copy_32.png"))); // NOI18N
        btnDescarte1.setText("Duplicar");
        btnDescarte1.setFocusable(false);
        btnDescarte1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescarte1.setPreferredSize(new java.awt.Dimension(60, 60));
        btnDescarte1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDescarte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescarte1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDescarte1);

        javax.swing.GroupLayout pnlColunasLayout = new javax.swing.GroupLayout(pnlColunas);
        pnlColunas.setLayout(pnlColunasLayout);
        pnlColunasLayout.setHorizontalGroup(
            pnlColunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlColunasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlColunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlColunasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisar))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlColunasLayout.setVerticalGroup(
            pnlColunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColunasLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlColunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblPaneMetodologia.addTab("Registro de Soluções", pnlColunas);

        pnlAuditTrail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Auditoria Coluna"));

        tblAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coluna_Id", "Versão", "MOD", "Cod_SAP", "Cod_SAP_MOD", "Tipo", "Tipo_MOD", "Fabricante", "Fabricante_MOD", "Marca", "Marca_MOD", "Fase", "Fase_MOD", "Tamanho", "Tamanho_MOD", "Diametro", "Diametro_MOD", "Particula", "Particula_MOD", "Part_Number", "Part_Number_MOD", "Obs", "Obs_MOD", "Computador / AD_User ", "Usuario", "Data Modificação", "Motivo", "Validação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAuditoria.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblAuditoria);
        if (tblAuditoria.getColumnModel().getColumnCount() > 0) {
            tblAuditoria.getColumnModel().getColumn(0).setMinWidth(80);
            tblAuditoria.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblAuditoria.getColumnModel().getColumn(1).setMinWidth(80);
            tblAuditoria.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblAuditoria.getColumnModel().getColumn(1).setMaxWidth(80);
            tblAuditoria.getColumnModel().getColumn(2).setMinWidth(100);
            tblAuditoria.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblAuditoria.getColumnModel().getColumn(2).setMaxWidth(100);
            tblAuditoria.getColumnModel().getColumn(23).setMinWidth(200);
            tblAuditoria.getColumnModel().getColumn(23).setPreferredWidth(200);
            tblAuditoria.getColumnModel().getColumn(24).setMinWidth(150);
            tblAuditoria.getColumnModel().getColumn(24).setPreferredWidth(150);
            tblAuditoria.getColumnModel().getColumn(25).setMinWidth(120);
            tblAuditoria.getColumnModel().getColumn(25).setPreferredWidth(120);
            tblAuditoria.getColumnModel().getColumn(26).setMinWidth(800);
            tblAuditoria.getColumnModel().getColumn(26).setPreferredWidth(800);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        txtPesquisarAuditoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarAuditoriaKeyReleased(evt);
            }
        });

        jLabel5.setText("Pesquisar:");

        javax.swing.GroupLayout pnlAuditoriaLayout = new javax.swing.GroupLayout(pnlAuditoria);
        pnlAuditoria.setLayout(pnlAuditoriaLayout);
        pnlAuditoriaLayout.setHorizontalGroup(
            pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAuditoriaLayout.createSequentialGroup()
                .addGroup(pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlAuditoriaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarAuditoria)))
                .addContainerGap())
        );
        pnlAuditoriaLayout.setVerticalGroup(
            pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuditoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAuditTrailLayout = new javax.swing.GroupLayout(pnlAuditTrail);
        pnlAuditTrail.setLayout(pnlAuditTrailLayout);
        pnlAuditTrailLayout.setHorizontalGroup(
            pnlAuditTrailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuditTrailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAuditoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAuditTrailLayout.setVerticalGroup(
            pnlAuditTrailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuditTrailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAuditoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblPaneMetodologia.addTab("Audit Trail", pnlAuditTrail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tblPaneMetodologia)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tblPaneMetodologia)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        TableSorter.TableSorter(tblSolucoes, txtPesquisar);
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        abrir();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblSolucoes.getSelectedRow() != -1) {
            atualizar();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblSolucoes.getSelectedRow() != -1) {
            deletar();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        read();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtPesquisarAuditoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarAuditoriaKeyReleased
        TableSorter.TableSorter(tblAuditoria, txtPesquisarAuditoria);
    }//GEN-LAST:event_txtPesquisarAuditoriaKeyReleased

    private void tblSolucoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSolucoesMouseClicked
        if (evt.getClickCount() == 2) {
            atualizar();
        }
    }//GEN-LAST:event_tblSolucoesMouseClicked

    private void tblSolucoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSolucoesKeyReleased
        if (tblSolucoes.getSelectedRow() != -1) {
            if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                deletar();
            }
        }
    }//GEN-LAST:event_tblSolucoesKeyReleased

    private void btnEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtiquetaActionPerformed
        if (tblSolucoes.getSelectedRow() != -1) {
//            HashMap map = new HashMap();
//            try {
//                map.put("id_coluna", (Long) tblColuna.getValueAt(tblColuna.getSelectedRow(), 0));
//                map.put("img", Thread.currentThread().getClass().getResourceAsStream("/Reports/ArrowUp.png"));
//                Reports.imprimir("EtiquetaColuna.jasper", map);
//            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + ex);
//            }
        }
    }//GEN-LAST:event_btnEtiquetaActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        new FrmImprimirRelatorio(this, true).setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnDescarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescarteActionPerformed
        if (tblSolucoes.getSelectedRow() != -1) {
            //descartar();
        }
    }//GEN-LAST:event_btnDescarteActionPerformed

    private void btnReativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReativarActionPerformed
        if (tblSolucoes.getSelectedRow() != -1) {
            //reativar();
        }
    }//GEN-LAST:event_btnReativarActionPerformed

    private void btnDescarte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescarte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescarte1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroSolucaoReagente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmRegistroSolucaoReagente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDescarte;
    private javax.swing.JButton btnDescarte1;
    public static javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEtiqueta;
    public static javax.swing.JButton btnExcluir;
    public static javax.swing.JButton btnNovo;
    private javax.swing.JButton btnReativar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlAuditTrail;
    private javax.swing.JPanel pnlAuditoria;
    private javax.swing.JPanel pnlColunas;
    private javax.swing.JTable tblAuditoria;
    private javax.swing.JTabbedPane tblPaneMetodologia;
    private javax.swing.JTable tblSolucoes;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtPesquisarAuditoria;
    // End of variables declaration//GEN-END:variables

    public final void read() {
        DefaultTableModel model = (DefaultTableModel) tblSolucoes.getModel();
        RegistroSolucaoReagenteDAO regsolReagenteDAO = new RegistroSolucaoReagenteDAO();
        model.setNumRows(0);
        try {
            for (RegistroSolucaoReagente solReagente : regsolReagenteDAO.findEntities(RegistroSolucaoReagente.class)) {
                model.addRow(new Object[]{
                    solReagente.getId(),
                    solReagente.getDescricao(),
                    solReagente.getLote(),
                    "",
                    solReagente.getCriador().getUsuario() + " / " + DataHora.getStringDate(solReagente.getDataPreparo()),
                    (solReagente.getAtivo() == null ? "" :
                    solReagente.getConferente().getUsuario() + " / " + DataHora.getStringDateTime(solReagente.getDataConferencia())),
                    solReagente.getVersion()
                });
            }
            //carregarAuditoria();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
        }
    }

    private void abrir() {
        try {
            new FrmRegistroSolucaoReagenteNovo(null, true).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
        } finally {
            read();
        }
    }

    private void atualizar() {
        if (AcessoSistema.editarDados(ACESSO)) {
            RegistroSolucaoReagenteDAO regsolReagenteDAO = new RegistroSolucaoReagenteDAO();
            try {
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                RegistroSolucaoReagente solReagente = regsolReagenteDAO.findById(RegistroSolucaoReagente.class,
                        (Long) tblSolucoes.getValueAt(tblSolucoes.getSelectedRow(), 0));
                new FrmRegistroSolucaoReagenteDados(null, true, solReagente).setVisible(true);
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
            } finally {
                read();
            }
        }
    }

    private void deletar() {
        if (AcessoSistema.deletarDados(ACESSO)) {
            RegistroSolucaoReagenteDAO regsolReagenteDAO = new RegistroSolucaoReagenteDAO();
            Senha senha = new Senha();
            try {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Realmente deseja Excluir esse registro?", "Aviso", JOptionPane.YES_NO_OPTION);
                if (dialogResult == 0) {
                    if (senha.Salvar()) {
                        RegistroSolucaoReagente solReagente = regsolReagenteDAO.findById(RegistroSolucaoReagente.class,
                                (Long) tblSolucoes.getValueAt(tblSolucoes.getSelectedRow(), 0));
                        regsolReagenteDAO.remover(RegistroSolucaoReagente.class, solReagente.getId());
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao excuir o dado: " + e.getMessage(), "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
            } finally {
                read();
            }
        }
    }

    private void carregarAuditoria() {
//        DefaultTableModel model = (DefaultTableModel) tblAuditoria.getModel();
//        SolucaoReagenteDAO solReagenteDAO = new SolucaoReagenteDAO();
//        model.setNumRows(0);
//        try {
//            for (SolucaoReagente solReagente : solReagenteDAO.readAuditoria()) {
//                model.addRow(new Object[]{
//                    col.getId(),
//                    col.getVersion(),
//                    col.getAudit().getMOD() == 0 ? "Criado"
//                    : (col.getAudit().getMOD() == 1 ? "Modificado" : "Removido"),
//                    col.getCodigoSap(),
//                    col.getCodigoSap_MOD() == false ? "Não Alterado" : "Alterado",
//                    col.getTipoColuna().getId(),
//                    col.getTipoColuna_MOD() == false ? "Não Alterado" : "Alterado",
//                    col.getFabricanteColuna().getId(),
//                    col.getFabricanteColuna_MOD() == false ? "Não Alterado" : "Alterado",
//                    col.getMarcaColuna().getId(),
//                    col.getMarcaColuna_MOD() == false ? "Não Alterado" : "Alterado",
//                    col.getFaseColuna().getId(),
//                    col.getFaseColuna_MOD() == false ? "Não Alterado" : "Alterado",
//                    col.getTamanhoColuna().getId(),
//                    col.getTamanhoColuna_MOD() == false ? "Não Alterado" : "Alterado",
//                    col.getDiametroColuna().getId(),
//                    col.getDiametroColuna_MOD() == false ? "Não Alterado" : "Alterado",
//                    col.getParticulaColuna().getId(),
//                    col.getPartNumber(),
//                    col.getPartNumber_MOD() == false ? "Não Alterado" : "Alterado",
//                    col.getObs(),
//                    col.getObs_MOD() == false ? "Não Alterado" : "Alterado",
//                    col.getAudit().getComputador() + " / " + col.getAudit().getUserComputador(),
//                    col.getAudit().getUltimaModificacaoPor(),
//                    DataHora.getStringDateTime(col.getAudit().getUltimaModificacao()),
//                    col.getAudit().getMotivo()
//                });
//            }
//        } catch (Exception e) {
//        }

    }

}
