/*
 * Copyright (C) 2018 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.config;

import br.com.lablims.dao.SegurancaDAO;
import br.com.lablims.dao.SistemaDAO;
import br.com.lablims.model.Seguranca;
import br.com.lablims.util.Senha;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.SpinnerNumberModel;
import br.com.lablims.model.Sistema;
import br.com.lablims.util.DataHora;
import br.com.lablims.util.Frames;
import br.com.lablims.util.TableSorter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael.lopes
 */
public class FrmSistemaConfig extends javax.swing.JDialog {

    /**
     * Creates new form FrmLogOffSystem
     *
     * @param parent
     * @param modal
     */
    public FrmSistemaConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Frames.setUpFrame(this, "Configurar Sistema", true);
        SpinnerNumberModel model1 = new SpinnerNumberModel(0, 0, 10, 1);
        SpinnerNumberModel model2 = new SpinnerNumberModel(0, 0, 10, 1);
        SpinnerNumberModel model3 = new SpinnerNumberModel(0, 0, 1000, 1);
        SpinnerNumberModel model4 = new SpinnerNumberModel(0, 0, 1000, 1);
        txtTamanhoSenha.setModel(model1);
        txtFalhaAcesso.setModel(model2);
        txtExpirarSenha.setModel(model3);
        txtAutoLogoff.setModel(model4);
        carregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomePrograma = new javax.swing.JTextField();
        txtCriador = new javax.swing.JTextField();
        txtDetalhes = new javax.swing.JTextField();
        txtVersaoPrograma = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBancoDados = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        txtDataVersao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFalhaAcesso = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTamanhoSenha = new javax.swing.JSpinner();
        txtAutoLogoff = new javax.swing.JSpinner();
        txtExpirarSenha = new javax.swing.JSpinner();
        btnCriptografia = new javax.swing.JToggleButton();
        btnValidar = new javax.swing.JToggleButton();
        btnMotivo = new javax.swing.JToggleButton();
        btnSenhaLetras = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlAuditoria = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAuditoria = new javax.swing.JTable();
        txtPesquisarAuditoria = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema"));

        jLabel3.setText("Nome do Sistema:");

        jLabel5.setText("Versão:");

        jLabel6.setText("Detalhes:");

        jLabel8.setText("Criador:");

        txtNomePrograma.setEditable(false);
        txtNomePrograma.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtCriador.setEditable(false);
        txtCriador.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtDetalhes.setEditable(false);
        txtDetalhes.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtVersaoPrograma.setEditable(false);
        txtVersaoPrograma.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel14.setText("Banco de Dados:");

        txtBancoDados.setEditable(false);
        txtBancoDados.setBackground(new java.awt.Color(240, 240, 240));
        txtBancoDados.setColumns(3);
        txtBancoDados.setRows(3);
        jScrollPane1.setViewportView(txtBancoDados);

        jLabel18.setText("Versionamento:");

        txtDataVersao.setEditable(false);
        txtDataVersao.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomePrograma)
                    .addComponent(txtCriador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDetalhes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVersaoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCriador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVersaoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setText("Cancelar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Regras de Segurança"));

        jLabel2.setText("N° de Falhas Acesso:");

        jLabel4.setText("Auto Logoff:");

        jLabel7.setText("Tamanho da Senha:");

        jLabel9.setText("Senha Alfanumérica:");

        jLabel10.setText("Criptografia:");

        jLabel11.setText("Campo Motivo:");

        jLabel12.setText("Validar antes de Salvar:");

        jLabel13.setText("Expirar Senha:");

        btnCriptografia.setPreferredSize(new java.awt.Dimension(33, 24));
        btnCriptografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriptografiaActionPerformed(evt);
            }
        });

        btnValidar.setPreferredSize(new java.awt.Dimension(33, 24));
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnMotivo.setPreferredSize(new java.awt.Dimension(33, 24));
        btnMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotivoActionPerformed(evt);
            }
        });

        btnSenhaLetras.setPreferredSize(new java.awt.Dimension(33, 24));
        btnSenhaLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenhaLetrasActionPerformed(evt);
            }
        });

        jLabel15.setText("dias");

        jLabel16.setText("Tentativas");

        jLabel17.setText("min");

        jLabel19.setText("Caracteres");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtFalhaAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtAutoLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTamanhoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtExpirarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(btnCriptografia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnValidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSenhaLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamanhoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSenhaLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCriptografia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExpirarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFalhaAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutoLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Segurança do Sistema", jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Auditoria Segurança"));

        tblAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Regra_Id", "Versão", "MOD", "Regra", "Valor", "Valor_MOD", "Computador / AD_User ", "Usuario", "Data Modificação", "Motivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAuditoria.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblAuditoria);
        if (tblAuditoria.getColumnModel().getColumnCount() > 0) {
            tblAuditoria.getColumnModel().getColumn(0).setMinWidth(80);
            tblAuditoria.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblAuditoria.getColumnModel().getColumn(0).setMaxWidth(80);
            tblAuditoria.getColumnModel().getColumn(1).setMinWidth(80);
            tblAuditoria.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblAuditoria.getColumnModel().getColumn(1).setMaxWidth(80);
            tblAuditoria.getColumnModel().getColumn(2).setMinWidth(100);
            tblAuditoria.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblAuditoria.getColumnModel().getColumn(2).setMaxWidth(100);
            tblAuditoria.getColumnModel().getColumn(3).setMinWidth(150);
            tblAuditoria.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblAuditoria.getColumnModel().getColumn(3).setMaxWidth(150);
            tblAuditoria.getColumnModel().getColumn(4).setMinWidth(80);
            tblAuditoria.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblAuditoria.getColumnModel().getColumn(4).setMaxWidth(80);
            tblAuditoria.getColumnModel().getColumn(5).setMinWidth(100);
            tblAuditoria.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblAuditoria.getColumnModel().getColumn(5).setMaxWidth(100);
            tblAuditoria.getColumnModel().getColumn(6).setMinWidth(300);
            tblAuditoria.getColumnModel().getColumn(6).setPreferredWidth(300);
            tblAuditoria.getColumnModel().getColumn(7).setMinWidth(200);
            tblAuditoria.getColumnModel().getColumn(7).setPreferredWidth(200);
            tblAuditoria.getColumnModel().getColumn(8).setMinWidth(200);
            tblAuditoria.getColumnModel().getColumn(8).setPreferredWidth(200);
            tblAuditoria.getColumnModel().getColumn(9).setMinWidth(400);
            tblAuditoria.getColumnModel().getColumn(9).setPreferredWidth(400);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        txtPesquisarAuditoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarAuditoriaKeyReleased(evt);
            }
        });

        jLabel20.setText("Pesquisar:");

        javax.swing.GroupLayout pnlAuditoriaLayout = new javax.swing.GroupLayout(pnlAuditoria);
        pnlAuditoria.setLayout(pnlAuditoriaLayout);
        pnlAuditoriaLayout.setHorizontalGroup(
            pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAuditoriaLayout.createSequentialGroup()
                .addGroup(pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlAuditoriaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarAuditoria)))
                .addContainerGap())
        );
        pnlAuditoriaLayout.setVerticalGroup(
            pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuditoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAuditoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAuditoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Audit Trail", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Senha senha = new Senha();
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (senha.Salvar()) {
            atualizar();
            dispose();
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        fechar();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnCriptografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriptografiaActionPerformed
        if (btnCriptografia.isSelected()) {
            btnCriptografia.setText("ON");
            btnCriptografia.setSelected(true);
            btnCriptografia.setBackground(Color.GREEN.darker());
        } else {
            btnCriptografia.setText("OFF");
            btnCriptografia.setSelected(false);
            btnCriptografia.setBackground(Color.RED.darker());
        }
    }//GEN-LAST:event_btnCriptografiaActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        if (btnValidar.isSelected()) {
            btnValidar.setText("ON");
            btnValidar.setSelected(true);
            btnValidar.setBackground(Color.GREEN.darker());
        } else {
            btnValidar.setText("OFF");
            btnValidar.setSelected(false);
            btnValidar.setBackground(Color.RED.darker());
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotivoActionPerformed
        if (btnMotivo.isSelected()) {
            btnMotivo.setText("ON");
            btnMotivo.setSelected(true);
            btnMotivo.setBackground(Color.GREEN.darker());
        } else {
            btnMotivo.setText("OFF");
            btnMotivo.setSelected(false);
            btnMotivo.setBackground(Color.RED.darker());
        }
    }//GEN-LAST:event_btnMotivoActionPerformed

    private void btnSenhaLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenhaLetrasActionPerformed
        if (btnSenhaLetras.isSelected()) {
            btnSenhaLetras.setText("ON");
            btnSenhaLetras.setSelected(true);
            btnSenhaLetras.setBackground(Color.GREEN.darker());
        } else {
            btnSenhaLetras.setText("OFF");
            btnSenhaLetras.setSelected(false);
            btnSenhaLetras.setBackground(Color.RED.darker());
        }
    }//GEN-LAST:event_btnSenhaLetrasActionPerformed

    private void txtPesquisarAuditoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarAuditoriaKeyReleased
        TableSorter.TableSorter(tblAuditoria, txtPesquisarAuditoria);
    }//GEN-LAST:event_txtPesquisarAuditoriaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmSistemaConfig dialog = new FrmSistemaConfig(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCriptografia;
    private javax.swing.JButton btnFechar;
    private javax.swing.JToggleButton btnMotivo;
    public static javax.swing.JButton btnSalvar;
    private javax.swing.JToggleButton btnSenhaLetras;
    private javax.swing.JToggleButton btnValidar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlAuditoria;
    private javax.swing.JTable tblAuditoria;
    private javax.swing.JSpinner txtAutoLogoff;
    private javax.swing.JTextArea txtBancoDados;
    private javax.swing.JTextField txtCriador;
    private javax.swing.JTextField txtDataVersao;
    private javax.swing.JTextField txtDetalhes;
    private javax.swing.JSpinner txtExpirarSenha;
    private javax.swing.JSpinner txtFalhaAcesso;
    private javax.swing.JTextField txtNomePrograma;
    private javax.swing.JTextField txtPesquisarAuditoria;
    private javax.swing.JSpinner txtTamanhoSenha;
    private javax.swing.JTextField txtVersaoPrograma;
    // End of variables declaration//GEN-END:variables

    private void carregar() {
        try {
            SistemaDAO sysDAO = new SistemaDAO();
            Sistema sys = sysDAO.findById(Sistema.class, 1L);
            txtNomePrograma.setText(sys.getSistemaNome());
            txtCriador.setText(sys.getSistemaCriador());
            txtDetalhes.setText(sys.getDetalhes());
            txtBancoDados.setText(sysDAO.infoBancoDados());
            txtDataVersao.setText(DataHora.getStringDateTime(sys.getSistemaDataUpdate()));
            try {
                StringBuilder sb = new StringBuilder();
                sb.append(sys.getMajorVersion()).append(".");
                sb.append(sys.getMinorVersion()).append(".");
                sb.append(sys.getPathVersion()).append(".");
                sb.append(sys.getQualifierVersion()).append(".");
                sb.append(sys.getBuilderVersao());
                txtVersaoPrograma.setText(sb.toString());
            } catch (Exception e) {
                txtVersaoPrograma.setText("0");
            }
            SegurancaDAO segDAO = new SegurancaDAO();
            for (Seguranca seg : segDAO.findEntities(Seguranca.class)) {
                switch (seg.getTipo()) {
                    case Seguranca.TAM_SENHA:
                        txtTamanhoSenha.setValue(seg.getNumero());
                        break;
                    case Seguranca.LETRAS:
                        btnSenhaLetras.setSelected(seg.getNumero() == 1);
                        if (btnSenhaLetras.isSelected()) {
                            btnSenhaLetras.setText("ON");
                            btnSenhaLetras.setSelected(true);
                            btnSenhaLetras.setBackground(Color.GREEN.darker());
                        } else {
                            btnSenhaLetras.setText("OFF");
                            btnSenhaLetras.setSelected(false);
                            btnSenhaLetras.setBackground(Color.RED.darker());
                        }
                        break;
                    case Seguranca.CRIPTO:
                        btnCriptografia.setSelected(seg.getNumero() == 1);
                        if (btnCriptografia.isSelected()) {
                            btnCriptografia.setText("ON");
                            btnCriptografia.setSelected(true);
                            btnCriptografia.setBackground(Color.GREEN.darker());
                        } else {
                            btnCriptografia.setText("OFF");
                            btnCriptografia.setSelected(false);
                            btnCriptografia.setBackground(Color.RED.darker());
                        }
                        break;
                    case Seguranca.MOTIVO:
                        btnMotivo.setSelected(seg.getNumero() == 1);
                        if (btnMotivo.isSelected()) {
                            btnMotivo.setText("ON");
                            btnMotivo.setSelected(true);
                            btnMotivo.setBackground(Color.GREEN.darker());
                        } else {
                            btnMotivo.setText("OFF");
                            btnMotivo.setSelected(false);
                            btnMotivo.setBackground(Color.RED.darker());
                        }
                        break;
                    case Seguranca.VALIDAR:
                        btnValidar.setSelected(seg.getNumero() == 1);
                        if (btnValidar.isSelected()) {
                            btnValidar.setText("ON");
                            btnValidar.setSelected(true);
                            btnValidar.setBackground(Color.GREEN.darker());
                        } else {
                            btnValidar.setText("OFF");
                            btnValidar.setSelected(false);
                            btnValidar.setBackground(Color.RED.darker());
                        }
                        break;
                    case Seguranca.EXPIRAR:
                        txtExpirarSenha.setValue(seg.getNumero());
                        break;
                    case Seguranca.FALHA:
                        txtFalhaAcesso.setValue(seg.getNumero());
                        break;
                    case Seguranca.FECHAR:
                        txtAutoLogoff.setValue(seg.getNumero());
                        break;
                }
            }
            carregarAuditoria();
        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void atualizar() {
        SegurancaDAO segDAO = new SegurancaDAO();
        try {
            Seguranca seg1 = segDAO.findByTipo(Seguranca.TAM_SENHA);
            seg1.setNumero((Integer) txtTamanhoSenha.getValue());
            segDAO.salvar(seg1);

            Seguranca seg2 = segDAO.findByTipo(Seguranca.EXPIRAR);
            seg2.setNumero((Integer) txtExpirarSenha.getValue());
            segDAO.salvar(seg2);

            Seguranca seg3 = segDAO.findByTipo(Seguranca.FALHA);
            seg3.setNumero((Integer) txtFalhaAcesso.getValue());
            segDAO.salvar(seg3);

            Seguranca seg4 = segDAO.findByTipo(Seguranca.FECHAR);
            seg4.setNumero((Integer) txtAutoLogoff.getValue());
            segDAO.salvar(seg4);

            Seguranca seg5 = segDAO.findByTipo(Seguranca.CRIPTO);
            seg5.setNumero(btnCriptografia.isSelected() ? 1 : 0);
            segDAO.salvar(seg5);

            Seguranca seg6 = segDAO.findByTipo(Seguranca.MOTIVO);
            seg6.setNumero(btnMotivo.isSelected() ? 1 : 0);
            segDAO.salvar(seg6);

            Seguranca seg7 = segDAO.findByTipo(Seguranca.VALIDAR);
            seg7.setNumero(btnValidar.isSelected() ? 1 : 0);
            segDAO.salvar(seg7);

            Seguranca seg8 = segDAO.findByTipo(Seguranca.LETRAS);
            seg8.setNumero(btnSenhaLetras.isSelected() ? 1 : 0);
            segDAO.salvar(seg8);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
        }
    }

    private void fechar() {
        Frames.fecharFrame(this);
    }

    private void carregarAuditoria() {
        DefaultTableModel model = (DefaultTableModel) tblAuditoria.getModel();
        SegurancaDAO segDAO = new SegurancaDAO();
        model.setNumRows(0);
        try {
            for (Seguranca seg : segDAO.readSegurancaAuditoria()) {
                model.addRow(new Object[]{
                    seg.getId(),
                    seg.getVersion(),
                    seg.getAudit().getMOD() == 0 ? "Criado" : (seg.getAudit().getMOD() == 1 ? "Modificado" : "Removido"),
                    seg.getTipo(),
                    seg.getNumero(),
                    seg.getNumero_MOD() == false ? "Não Alterado" : "Alterado",
                    seg.getAudit().getComputador() + " / " + seg.getAudit().getUserComputador(),
                    seg.getAudit().getUltimaModificacaoPor(),
                    DataHora.getStringDateTime(seg.getAudit().getUltimaModificacao()),
                    seg.getAudit().getMotivo()
                });
            }
        } catch (Exception e) {
        }
    }

}
