package br.com.lablims.view.config;

import br.com.lablims.dao.GrupoDAO;
import br.com.lablims.dao.SetorDAO;
import br.com.lablims.dao.UsuarioDAO;
import br.com.lablims.view.config.FrmSalvar;
import br.com.lablims.model.Grupo;
import br.com.lablims.model.Setor;
import br.com.lablims.model.Usuario;
import br.com.lablims.util.ComboBox;
import br.com.lablims.util.Cript;
import java.util.Arrays;
import javax.swing.JOptionPane;
import br.com.lablims.util.Validate;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import br.com.lablims.connection.ConnectionFactory;
import br.com.lablims.model.Senha;

/**
 *
 * @author rafael.lopes
 */
public class FrmUsuarioDados extends javax.swing.JDialog {

    private Usuario usuario;
    private boolean novoUsuario = false;
    private final TreeMap<Integer, String> categoryMapGrupo = new TreeMap<>();
    private final TreeMap<Integer, String> categoryMapSetor = new TreeMap<>();

    /**
     * Creates new form FrmUsuarioColuna
     *
     * @param parent
     * @param modal
     */
    public FrmUsuarioDados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Dados do Usuário");
        setResizable(false);
        limparCampos();
        novoUsuario = true;
        txtUsuario.setEditable(true);
        readTurno();
        readGrupo();
        readSetor();
    }

    public FrmUsuarioDados(java.awt.Frame parent, boolean modal, Usuario user) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Dados do Usuário");
        setResizable(false);
        limparCampos();
        usuario = user;
        txtUsuario.setEditable(false);
        readTurno();
        readGrupo();
        readSetor();
        carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvarUsuario = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCracha = new javax.swing.JFormattedTextField();
        cmbStatus = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbTurno = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmbGrupo = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        cmbSetor = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ckbAlterarSenha = new javax.swing.JCheckBox();
        txtNovaSenha = new javax.swing.JPasswordField();
        txtConfirmaSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSalvarUsuario.setText("Ok");
        btnSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuarioActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel1.setText("Usuário:");

        jLabel2.setText("Nome:");

        jLabel3.setText("E-mail:");

        jLabel10.setText("Crachá:");

        try {
            txtCracha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Desbilitado" }));
        cmbStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setText("Status:");

        jLabel9.setText("Turno:");

        cmbTurno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel11.setText("Grupo:");

        cmbGrupo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel28.setText("Setor:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbStatus, 0, 265, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome)
                            .addComponent(txtEmail)
                            .addComponent(txtCracha, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(txtUsuario))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmbGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCracha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cmbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));

        jLabel5.setText("Nova Senha:");

        jLabel6.setText("Confirmar Nova Senha:");

        ckbAlterarSenha.setText("Alterar senha no próximo login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ckbAlterarSenha)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtConfirmaSenha)
                    .addComponent(txtNovaSenha))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbAlterarSenha))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarUsuario)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuarioActionPerformed
        Validate val = new Validate();
        Senha senha = new Senha();
        EntityManager em = ConnectionFactory.em(true);
        try {
            if (txtUsuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Usuário inválido");
                txtUsuario.requestFocus();
            } else if (txtNome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nome inválido");
                txtNome.requestFocus();
            } else if (!val.isEmail(txtEmail.getText())) {
                JOptionPane.showMessageDialog(null, "Email inválido");
                txtEmail.requestFocus();
            } else if (txtCracha.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Crachá inválido");
                txtCracha.requestFocus();
            } else if (cmbTurno.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Turno inválido");
                cmbTurno.requestFocus();
            } else if (cmbGrupo.getSelectedItem().toString().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Grupo inválido");
                cmbGrupo.requestFocus();
            } else if (cmbSetor.getSelectedItem().toString().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Setor inválido");
                cmbSetor.requestFocus();
            } else if (!new String(txtNovaSenha.getPassword()).equals(new String(txtConfirmaSenha.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Senhas não conferem: ");
                txtNovaSenha.setText(null);
                txtConfirmaSenha.setText(null);
                txtNovaSenha.requestFocus();
            } else if (novoUsuario) {
                Usuario u = new Usuario();
                u.setUsuario(txtUsuario.getText());
                if (UsuarioDAO.checkUserIsExits(em, u)) {
                    JOptionPane.showMessageDialog(null, "Usuário já existe!", "Alerta", JOptionPane.ERROR_MESSAGE);
                    txtUsuario.requestFocus();
                } else {
                    FrmSalvar frmSalvar = new FrmSalvar(null, true, em, senha);
                    frmSalvar.setVisible(true);
                    if (senha.getSenha()) {
                        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                        criarUsuario();
                        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    }
                }
            } else {
                FrmSalvar frmSalvar = new FrmSalvar(null, true, em, senha);
                frmSalvar.setVisible(true);
                if (senha.getSenha()) {
                    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    atulizarUsuario();
                    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                }
            }
        } catch (Exception e) {
        } finally {
            em.close();
        }
    }//GEN-LAST:event_btnSalvarUsuarioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarioDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarioDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarioDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarioDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmUsuarioDados dialog = new FrmUsuarioDados(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnSalvarUsuario;
    private javax.swing.JCheckBox ckbAlterarSenha;
    private javax.swing.JComboBox cmbGrupo;
    private javax.swing.JComboBox cmbSetor;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JComboBox cmbTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JFormattedTextField txtCracha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtNovaSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void criarUsuario() {
        UsuarioDAO userDAO = new UsuarioDAO();
        Usuario user = new Usuario();
        Grupo grup = new Grupo();
        Setor setor = new Setor();
        EntityManager em = ConnectionFactory.em(true);
        try {
            user.setUsuario(txtUsuario.getText().toLowerCase());
            user.setPass(("").equals(Arrays.toString(txtNovaSenha.getPassword()))
                    ? Cript.md5(new String(txtNovaSenha.getPassword()))
                    : Cript.md5("123456"));
            user.setNome(txtNome.getText().trim().toUpperCase());
            user.setEmail(txtEmail.getText().toLowerCase());
            user.setLock((Integer) cmbStatus.getSelectedIndex() == 1);
            grup.setId(ComboBox.getKeyForValue(cmbGrupo.getSelectedItem().toString(), categoryMapGrupo));
            user.setGrupo(grup);
            user.setCracha(txtCracha.getText());
            user.setTurno(cmbTurno.getSelectedItem().toString());
            user.setChange_pass(ckbAlterarSenha.isSelected());
            setor.setId(ComboBox.getKeyForValue(cmbSetor.getSelectedItem().toString(), categoryMapSetor));
            user.setSetor(setor);
            userDAO.salvar(em, user);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
        } finally {
            em.close();
            dispose();
        }
    }

    private void carregarDados() {
        UsuarioDAO userDAO = new UsuarioDAO();
        EntityManager em = ConnectionFactory.em(true);
        try {
            userDAO.findById(em, Usuario.class, usuario.getId());
            txtUsuario.setText(usuario.getUsuario().toLowerCase());
            txtNome.setText(usuario.getNome());
            txtEmail.setText(usuario.getEmail());
            cmbStatus.setSelectedIndex(usuario.getLock() ? 1 : 0);
            txtCracha.setText(usuario.getCracha());
            ckbAlterarSenha.setSelected(usuario.getChange_pass());
            String[] turno = {usuario.getTurno()};
            cmbTurno.setSelectedItem(turno[0]);
            String[] grupo = {usuario.getGrupo().getGrupoNome()};
            cmbGrupo.setSelectedItem(grupo[0]);
            String[] setor = {usuario.getSetor().getSiglaSetor()};
            cmbSetor.setSelectedItem(setor[0]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
        } finally {
            em.close();
        }
    }

    private void atulizarUsuario() {
        UsuarioDAO userDAO = new UsuarioDAO();
        Grupo grup = new Grupo();
        Setor setor = new Setor();
        EntityManager em = ConnectionFactory.em(true);
        try {
            usuario.setUsuario(txtUsuario.getText().toLowerCase());
            usuario.setNome(txtNome.getText().toUpperCase());
            usuario.setEmail(txtEmail.getText());
            usuario.setLock((Integer) cmbStatus.getSelectedIndex() == 1);
            grup.setId(ComboBox.getKeyForValue(cmbGrupo.getSelectedItem().toString(), categoryMapGrupo));
            usuario.setGrupo(grup);
            usuario.setCracha(txtCracha.getText());
            usuario.setTurno(cmbTurno.getSelectedItem().toString());
            usuario.setChange_pass(ckbAlterarSenha.isSelected());
            setor.setId(ComboBox.getKeyForValue(cmbSetor.getSelectedItem().toString(), categoryMapSetor));
            usuario.setSetor(setor);
            if (!new String(txtNovaSenha.getPassword()).trim().isEmpty()) {
                if (!new String(txtNovaSenha.getPassword()).equals(new String(txtConfirmaSenha.getPassword()))) {
                    JOptionPane.showMessageDialog(null, "Senhas não conferem: ");
                    txtNovaSenha.setText(null);
                    txtConfirmaSenha.setText(null);
                } else {
                    usuario.setPass(Cript.SHA(new String(txtNovaSenha.getPassword())));
//                    userDAO.updateUserPassword(usuario);
                    userDAO.salvar(em, usuario);
                }
            } else {
                userDAO.salvar(em, usuario);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar dados: " + e);
        } finally {
            em.close();
            dispose();
        }

    }

    private void limparCampos() {
        txtUsuario.setText(null);
        txtNome.setText(null);
        txtEmail.setText(null);
        txtCracha.setText(null);
        txtNovaSenha.setText(null);
        txtConfirmaSenha.setText(null);
        cmbStatus.setSelectedIndex(0);
        ckbAlterarSenha.setSelected(false);
    }

    public final void readTurno() {
        cmbTurno.removeAllItems();
        cmbTurno.addItem("1T");
        cmbTurno.addItem("2T");
        cmbTurno.addItem("3T");
        cmbTurno.addItem("Comercial");
    }

    public final void readGrupo() {
        cmbGrupo.removeAllItems();
        cmbGrupo.addItem("");
        categoryMapGrupo.clear();
        GrupoDAO grupDAO = new GrupoDAO();
        EntityManager em = ConnectionFactory.em(true);
        try {
            for (Grupo grup : grupDAO.findEntities(em, Grupo.class)) {
                Integer id = grup.getId();
                String name = grup.getGrupoNome();
                cmbGrupo.addItem(name);
                categoryMapGrupo.put(id, name);
            }
        } catch (Exception e) {
        } finally {
            em.close();
        }

    }

    public final void readSetor() {
        cmbSetor.removeAllItems();
        cmbSetor.addItem("");
        categoryMapSetor.clear();
        SetorDAO setorDAO = new SetorDAO();
        EntityManager em = ConnectionFactory.em(true);
        try {
            for (Setor setor : setorDAO.findEntities(em, Setor.class)) {
                Integer id = setor.getId();
                String name = setor.getSiglaSetor();
                cmbSetor.addItem(name);
                categoryMapSetor.put(id, name);
            }
        } catch (Exception e) {
        } finally {
            em.close();
        }

    }

}
