/*
 * Copyright (C) 2019 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.cristalia.colunas.principal;

import br.com.cristalia.biblioteca.authentication.FrmSenhaAlterar;
import br.com.cristalia.biblioteca.authentication.FrmUsuarioVisualizar;
import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import br.com.cristalia.biblioteca.dao.LoginDAO;
import br.com.cristalia.biblioteca.dao.SegurancaDAO;
import br.com.cristalia.biblioteca.dao.UsuarioDAO;
import br.com.cristalia.biblioteca.model.Seguranca;
import br.com.cristalia.biblioteca.model.Usuario;
import br.com.cristalia.biblioteca.util.AcessoSistema;
import br.com.cristalia.biblioteca.util.Frames;
import br.com.cristalia.biblioteca.util.MouseEventButton;
import br.com.cristalia.colunas.view.FrmColuna;
import br.com.cristalia.colunas.view.FrmColunaConfig;
import br.com.cristalia.colunas.view.FrmColunaStorage;
import br.com.cristalia.colunas.view.FrmColunaVaga;
import br.com.cristalia.colunas.view.FrmColunasCromatograficas;
import br.com.cristalia.colunas.view.FrmDocumentos;
import java.awt.AWTEvent;
import java.awt.Toolkit;
import java.awt.event.AWTEventListener;

/**
 * O <code>FrmPrincipal</code> implementa tela inicial do sistema
 *
 * @author rafae.lopes
 * @version 1.00
 */
public class FrmPrincipal extends javax.swing.JFrame {

    //private Timer timer;
    private Long timer;

    public FrmPrincipal() {
        initComponents();
        pnlColunas.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmColunasCromatograficas.class.getSimpleName())));
        pnlColunaStorage.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmColunaStorage.class.getSimpleName())));
        pnlColunaVaga.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmColunaVaga.class.getSimpleName())));
        pnlColunas.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmColuna.class.getSimpleName())));
        pnlDocumentos.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmDocumentos.class.getSimpleName())));
        pnlColunas.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmColunaConfig.class.getSimpleName())));
        carregar();
        checkTempoInatividade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblLogOut = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlTopMenu = new javax.swing.JPanel();
        lblLabMenuTop = new javax.swing.JLabel();
        lblLogoMenuTop = new javax.swing.JLabel();
        lblLimsMenuTop = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        pnlColunaStorage = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlDocumentos = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblLaboratorio = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlCadastroColunas = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnlColunas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlColunaVaga = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(892, 40));

        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_exit_25.png"))); // NOI18N
        lblLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLogOutMouseReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_reset_password_25.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_user_25.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });

        pnlTopMenu.setBackground(new java.awt.Color(181, 220, 237));
        pnlTopMenu.setPreferredSize(new java.awt.Dimension(0, 40));
        pnlTopMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLabMenuTop.setBackground(new java.awt.Color(153, 153, 153));
        lblLabMenuTop.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblLabMenuTop.setForeground(new java.awt.Color(0, 102, 102));
        lblLabMenuTop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLabMenuTop.setText("Lab");
        pnlTopMenu.add(lblLabMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        lblLogoMenuTop.setBackground(new java.awt.Color(255, 255, 255));
        lblLogoMenuTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoMenuTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_lablims_32.png"))); // NOI18N
        lblLogoMenuTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTopMenu.add(lblLogoMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 20, 40));

        lblLimsMenuTop.setBackground(new java.awt.Color(153, 153, 153));
        lblLimsMenuTop.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLimsMenuTop.setForeground(new java.awt.Color(67, 72, 79));
        lblLimsMenuTop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimsMenuTop.setText("L  MS");
        pnlTopMenu.add(lblLimsMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_chemistry_lab_32.png"))); // NOI18N
        jLabel15.setText("Colunas Cromatográficas");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(pnlTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogOut)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(lblLogOut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTopMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlPrincipal.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlColunaStorage.setBackground(new java.awt.Color(255, 255, 255));
        pnlColunaStorage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlColunaStorage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlColunaStorageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlColunaStorageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlColunaStorageMouseExited(evt);
            }
        });
        pnlColunaStorage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_arquivo.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlColunaStorage.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Storage");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlColunaStorage.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, -1));

        pnlDocumentos.setBackground(new java.awt.Color(255, 255, 255));
        pnlDocumentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDocumentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDocumentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDocumentosMouseExited(evt);
            }
        });
        pnlDocumentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_attach_32.png"))); // NOI18N
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Digitalizados");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, -1));

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Documentos");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 6, 110, -1));

        lblLaboratorio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLaboratorio.setText("Colunas Cromatográficas");

        pnlCadastroColunas.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadastroColunas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCadastroColunas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCadastroColunasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCadastroColunasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCadastroColunasMouseExited(evt);
            }
        });
        pnlCadastroColunas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_hplc_column.jpg"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCadastroColunas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Cadastro");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCadastroColunas.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, -1));

        pnlColunas.setBackground(new java.awt.Color(255, 255, 255));
        pnlColunas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlColunas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlColunasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlColunasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlColunasMouseExited(evt);
            }
        });
        pnlColunas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_coluna.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlColunas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Colunas");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlColunas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 20));

        pnlColunaVaga.setBackground(new java.awt.Color(255, 255, 255));
        pnlColunaVaga.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlColunaVaga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlColunaVagaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlColunaVagaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlColunaVagaMouseExited(evt);
            }
        });
        pnlColunaVaga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_location_update_32.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlColunaVaga.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel27.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Vagas");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlColunaVaga.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, -1));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLaboratorio)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(pnlColunaStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlColunaVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(pnlCadastroColunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 252, Short.MAX_VALUE))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaboratorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlColunaStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlColunaVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCadastroColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseReleased
        logout();
    }//GEN-LAST:event_lblLogOutMouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        trocarSenha();
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        dadosUsuario();
    }//GEN-LAST:event_jLabel5MouseReleased

    private void pnlColunaStorageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunaStorageMouseClicked
        Frames.carregarJFrame(FrmColunaStorage.class);
    }//GEN-LAST:event_pnlColunaStorageMouseClicked

    private void pnlColunaStorageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunaStorageMouseEntered
        MouseEventButton.setMouseEntered(pnlColunaStorage);
    }//GEN-LAST:event_pnlColunaStorageMouseEntered

    private void pnlColunaStorageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunaStorageMouseExited
        MouseEventButton.setMouseExited(pnlColunaStorage);
    }//GEN-LAST:event_pnlColunaStorageMouseExited

    private void pnlDocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentosMouseClicked
        Frames.carregarJFrame(FrmDocumentos.class);
    }//GEN-LAST:event_pnlDocumentosMouseClicked

    private void pnlDocumentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentosMouseEntered
        MouseEventButton.setMouseEntered(pnlDocumentos);
    }//GEN-LAST:event_pnlDocumentosMouseEntered

    private void pnlDocumentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentosMouseExited
        MouseEventButton.setMouseExited(pnlDocumentos);
    }//GEN-LAST:event_pnlDocumentosMouseExited

    private void pnlCadastroColunasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCadastroColunasMouseClicked
        Frames.carregarJFrame(FrmColuna.class);
    }//GEN-LAST:event_pnlCadastroColunasMouseClicked

    private void pnlCadastroColunasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCadastroColunasMouseEntered
        MouseEventButton.setMouseEntered(pnlCadastroColunas);
    }//GEN-LAST:event_pnlCadastroColunasMouseEntered

    private void pnlCadastroColunasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCadastroColunasMouseExited
        MouseEventButton.setMouseExited(pnlCadastroColunas);
    }//GEN-LAST:event_pnlCadastroColunasMouseExited

    private void pnlColunasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunasMouseClicked
        Frames.carregarJFrame(FrmColunasCromatograficas.class);
    }//GEN-LAST:event_pnlColunasMouseClicked

    private void pnlColunasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunasMouseEntered
        MouseEventButton.setMouseEntered(pnlColunas);
    }//GEN-LAST:event_pnlColunasMouseEntered

    private void pnlColunasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunasMouseExited
        MouseEventButton.setMouseExited(pnlColunas);
    }//GEN-LAST:event_pnlColunasMouseExited

    private void pnlColunaVagaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunaVagaMouseClicked
        Frames.carregarJFrame(FrmColunaVaga.class);
    }//GEN-LAST:event_pnlColunaVagaMouseClicked

    private void pnlColunaVagaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunaVagaMouseEntered
        MouseEventButton.setMouseEntered(pnlColunaVaga);
    }//GEN-LAST:event_pnlColunaVagaMouseEntered

    private void pnlColunaVagaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunaVagaMouseExited
        MouseEventButton.setMouseExited(pnlColunaVaga);
    }//GEN-LAST:event_pnlColunaVagaMouseExited

    /**
     * Método para criar o Form FrmPrincipal()
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblLabMenuTop;
    private javax.swing.JLabel lblLaboratorio;
    private javax.swing.JLabel lblLimsMenuTop;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblLogoMenuTop;
    private javax.swing.JPanel pnlCadastroColunas;
    private javax.swing.JPanel pnlColunaStorage;
    private javax.swing.JPanel pnlColunaVaga;
    private javax.swing.JPanel pnlColunas;
    private javax.swing.JPanel pnlDocumentos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTopMenu;
    // End of variables declaration//GEN-END:variables

    private void carregar() {
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        setIconImage(new Frames().getIcon());
        setTitle("Controle de Qualidade - Modulo CQ_Desktop - Usuário: " + System.getProperty("user"));

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                logout();
            }
        });
    }

    private void logout() {
        int option = JOptionPane.showConfirmDialog(
                null,
                "Tem certeza de que deseja fechar o aplicativo?",
                "Confirmação de Fechamento",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            LoginDAO loginDAO = new LoginDAO();
            UsuarioDAO userDAO = new UsuarioDAO();
            try {
                Usuario user = new UsuarioDAO().findById(Usuario.class,
                        Long.parseLong(System.getProperty("user_id")));
                loginDAO.logoffUsuario(user);
                userDAO.atualizarLogoffUsuario(user);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao Gravar Logout" + ex);
            }
            System.exit(0);
        }
    }

    private void checkTempoInatividade() {
        Long eventMask = AWTEvent.KEY_EVENT_MASK | AWTEvent.MOUSE_EVENT_MASK;
        Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {
            @Override
            public void eventDispatched(AWTEvent e) {
                timer = System.currentTimeMillis();
            }
        }, eventMask);
        timer = System.currentTimeMillis();
        new Thread(new Runnable() {
            @Override
            public void run() {
                Integer tempo;
                try {
                    tempo = new SegurancaDAO().findByTipo(Seguranca.FECHAR).getNumero();
                } catch (Exception ex) {
                    tempo = 120;
                }
                while (true) {
                    if (System.currentTimeMillis() - timer > tempo * 60000) {
                        System.exit(0);
                        break;
                    }
                }
            }
        }).start();
    }

    private void trocarSenha() {
        try {
            FrmSenhaAlterar frm = new FrmSenhaAlterar(null, true);
            frm.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Alterar Senha" + ex);
        }
    }

    private void dadosUsuario() {
        try {
            FrmUsuarioVisualizar frm = new FrmUsuarioVisualizar(null, true);
            frm.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Abrir" + ex);
        }

    }
}
