/*
 * Copyright (C) 2019 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.principal;

import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import br.com.lablims.dao.LoginDAO;
import br.com.lablims.dao.SegurancaDAO;
import br.com.lablims.dao.UsuarioDAO;
import br.com.lablims.model.Seguranca;
import br.com.lablims.model.Usuario;
import br.com.lablims.util.AcessoSistema;
import br.com.lablims.util.Frames;
import br.com.lablims.view.config.FrmSenhaAlterar;
import br.com.lablims.view.config.FrmUsuarioVisualizar;
import br.com.lablims.view.mp.PnlMateriaPrima;
import br.com.lablims.view.pa.PnlProdutoAcabado;
import java.awt.AWTEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import java.awt.event.AWTEventListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 * O <code>FrmPrincipal</code> implementa tela inicial do sistema
 *
 * @author rafae.lopes
 * @version 1.00
 */
public class FrmPrincipal extends javax.swing.JFrame {

    //private Timer timer;
    private Long timer;

    public FrmPrincipal() {
        initComponents();

        btnCadastro.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(PnlCadastro.class.getSimpleName())));
        btnConfig.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(PnlConfigurar.class.getSimpleName())));
        btnLaboratorio.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(PnlLaboratorio.class.getSimpleName())));
        btnDocumental.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(PnlDocumental.class.getSimpleName())));
        btnMateriaPrima.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(PnlMateriaPrima.class.getSimpleName())));
        btnProdutoAcabado.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(PnlProdutoAcabado.class.getSimpleName())));
        carregar();
        checkTempoInatividade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new javax.swing.JPanel();
        btnConfig = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblDashboard1 = new javax.swing.JLabel();
        btnLaboratorio = new javax.swing.JPanel();
        ind_7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnDocumental = new javax.swing.JPanel();
        ind_8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnMateriaPrima = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnProdutoAcabado = new javax.swing.JPanel();
        ind_9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLogOut = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlTopMenu = new javax.swing.JPanel();
        btnMenu = new javax.swing.JToggleButton();
        lblLabMenuTop = new javax.swing.JLabel();
        lblLogoMenuTop = new javax.swing.JLabel();
        lblLimsMenuTop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrincipal = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setPreferredSize(new java.awt.Dimension(250, 263));

        btnConfig.setBackground(new java.awt.Color(23, 35, 51));
        btnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnConfigMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_config_25.png"))); // NOI18N
        jLabel9.setText("Configurações");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnConfigLayout = new javax.swing.GroupLayout(btnConfig);
        btnConfig.setLayout(btnConfigLayout);
        btnConfigLayout.setHorizontalGroup(
            btnConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfigLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(0, 121, Short.MAX_VALUE))
        );
        btnConfigLayout.setVerticalGroup(
            btnConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfigLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCadastro.setBackground(new java.awt.Color(23, 35, 51));
        btnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadastroMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_cadastro_25.png"))); // NOI18N
        jLabel11.setText("Cadastro");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnCadastroLayout = new javax.swing.GroupLayout(btnCadastro);
        btnCadastro.setLayout(btnCadastroLayout);
        btnCadastroLayout.setHorizontalGroup(
            btnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCadastroLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCadastroLayout.setVerticalGroup(
            btnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCadastroLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblDashboard.setBackground(new java.awt.Color(153, 153, 153));
        lblDashboard.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(204, 204, 204));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDashboard.setText("L  MS");

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_lablims_100.png"))); // NOI18N
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDashboard1.setBackground(new java.awt.Color(153, 153, 153));
        lblDashboard1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lblDashboard1.setForeground(new java.awt.Color(0, 153, 153));
        lblDashboard1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDashboard1.setText("Lab");

        btnLaboratorio.setBackground(new java.awt.Color(23, 35, 51));
        btnLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaboratorioMousePressed(evt);
            }
        });

        ind_7.setOpaque(false);
        ind_7.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_7Layout = new javax.swing.GroupLayout(ind_7);
        ind_7.setLayout(ind_7Layout);
        ind_7Layout.setHorizontalGroup(
            ind_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_7Layout.setVerticalGroup(
            ind_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_laboratorio_25.png"))); // NOI18N
        jLabel14.setText("Laboratório");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnLaboratorioLayout = new javax.swing.GroupLayout(btnLaboratorio);
        btnLaboratorio.setLayout(btnLaboratorioLayout);
        btnLaboratorioLayout.setHorizontalGroup(
            btnLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLaboratorioLayout.createSequentialGroup()
                .addComponent(ind_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnLaboratorioLayout.setVerticalGroup(
            btnLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLaboratorioLayout.createSequentialGroup()
                .addComponent(ind_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnLaboratorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnDocumental.setBackground(new java.awt.Color(23, 35, 51));
        btnDocumental.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocumental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDocumentalMousePressed(evt);
            }
        });

        ind_8.setOpaque(false);
        ind_8.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_8Layout = new javax.swing.GroupLayout(ind_8);
        ind_8.setLayout(ind_8Layout);
        ind_8Layout.setHorizontalGroup(
            ind_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_8Layout.setVerticalGroup(
            ind_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_documento_25.png"))); // NOI18N
        jLabel15.setText("Documental");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnDocumentalLayout = new javax.swing.GroupLayout(btnDocumental);
        btnDocumental.setLayout(btnDocumentalLayout);
        btnDocumentalLayout.setHorizontalGroup(
            btnDocumentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDocumentalLayout.createSequentialGroup()
                .addComponent(ind_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnDocumentalLayout.setVerticalGroup(
            btnDocumentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDocumentalLayout.createSequentialGroup()
                .addComponent(ind_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnDocumentalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnMateriaPrima.setBackground(new java.awt.Color(23, 35, 51));
        btnMateriaPrima.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMateriaPrima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMateriaPrimaMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_materia_prima_25.png"))); // NOI18N
        jLabel10.setText("Matéria Prima");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnMateriaPrimaLayout = new javax.swing.GroupLayout(btnMateriaPrima);
        btnMateriaPrima.setLayout(btnMateriaPrimaLayout);
        btnMateriaPrimaLayout.setHorizontalGroup(
            btnMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMateriaPrimaLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnMateriaPrimaLayout.setVerticalGroup(
            btnMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMateriaPrimaLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnMateriaPrimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnProdutoAcabado.setBackground(new java.awt.Color(23, 35, 51));
        btnProdutoAcabado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProdutoAcabado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProdutoAcabadoMousePressed(evt);
            }
        });

        ind_9.setOpaque(false);
        ind_9.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_9Layout = new javax.swing.GroupLayout(ind_9);
        ind_9.setLayout(ind_9Layout);
        ind_9Layout.setHorizontalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_9Layout.setVerticalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_produto_acabado_25.png"))); // NOI18N
        jLabel16.setText("Produto Acabado");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnProdutoAcabadoLayout = new javax.swing.GroupLayout(btnProdutoAcabado);
        btnProdutoAcabado.setLayout(btnProdutoAcabadoLayout);
        btnProdutoAcabadoLayout.setHorizontalGroup(
            btnProdutoAcabadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProdutoAcabadoLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnProdutoAcabadoLayout.setVerticalGroup(
            btnProdutoAcabadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProdutoAcabadoLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnProdutoAcabadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout side_paneLayout = new javax.swing.GroupLayout(side_pane);
        side_pane.setLayout(side_paneLayout);
        side_paneLayout.setHorizontalGroup(
            side_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, side_paneLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(side_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDashboard1)
                    .addGroup(side_paneLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(side_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addComponent(btnLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDocumental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMateriaPrima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProdutoAcabado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        side_paneLayout.setVerticalGroup(
            side_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_paneLayout.createSequentialGroup()
                .addGroup(side_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(side_paneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(btnLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProdutoAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDocumental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(123, 123, 123));
        jPanel2.setPreferredSize(new java.awt.Dimension(892, 40));

        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_exit_25.png"))); // NOI18N
        lblLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLogOutMouseReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_reset_password_25.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_user_25.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });

        pnlTopMenu.setBackground(new java.awt.Color(23, 35, 51));
        pnlTopMenu.setPreferredSize(new java.awt.Dimension(0, 40));
        pnlTopMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_menu_25_2.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenu.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_menu_25_1.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        pnlTopMenu.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 43));

        lblLabMenuTop.setBackground(new java.awt.Color(153, 153, 153));
        lblLabMenuTop.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblLabMenuTop.setForeground(new java.awt.Color(0, 102, 102));
        lblLabMenuTop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLabMenuTop.setText("Lab");
        pnlTopMenu.add(lblLabMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        lblLogoMenuTop.setBackground(new java.awt.Color(255, 255, 255));
        lblLogoMenuTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoMenuTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_lablims_32.png"))); // NOI18N
        lblLogoMenuTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTopMenu.add(lblLogoMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 20, -1));

        lblLimsMenuTop.setBackground(new java.awt.Color(153, 153, 153));
        lblLimsMenuTop.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLimsMenuTop.setForeground(new java.awt.Color(67, 72, 79));
        lblLimsMenuTop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimsMenuTop.setText("L  MS");
        pnlTopMenu.add(lblLimsMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(pnlTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 627, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogOut)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(lblLogOut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(tblPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(side_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfigMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseReleased
        setColor(btnConfig);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btnCadastro, btnLaboratorio, btnDocumental, btnMateriaPrima, btnProdutoAcabado},
                new JPanel[]{ind_4, ind_7, ind_8, ind_3, ind_9});
        criarJanela("Configurações", new PnlConfigurar());
    }//GEN-LAST:event_btnConfigMouseReleased

    private void btnCadastroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMousePressed
        setColor(btnCadastro);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btnConfig, btnLaboratorio, btnDocumental, btnMateriaPrima, btnProdutoAcabado},
                new JPanel[]{ind_2, ind_7, ind_8, ind_3, ind_9});
        criarJanela("Cadastros", new PnlCadastro());
    }//GEN-LAST:event_btnCadastroMousePressed

    private void lblLogOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseReleased
        logout();
    }//GEN-LAST:event_lblLogOutMouseReleased

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        menu();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        trocarSenha();
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        dadosUsuario();
    }//GEN-LAST:event_jLabel5MouseReleased

    private void btnLaboratorioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorioMousePressed
        setColor(btnLaboratorio);
        ind_7.setOpaque(true);
        resetColor(new JPanel[]{btnConfig, btnCadastro, btnDocumental, btnMateriaPrima, btnProdutoAcabado},
                new JPanel[]{ind_2, ind_4, ind_8, ind_3, ind_9});
        criarJanela("Laboratório", new PnlLaboratorio());
    }//GEN-LAST:event_btnLaboratorioMousePressed

    private void btnDocumentalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentalMousePressed
        setColor(btnDocumental);
        ind_8.setOpaque(true);
        resetColor(new JPanel[]{btnConfig, btnCadastro, btnLaboratorio, btnMateriaPrima, btnProdutoAcabado},
                new JPanel[]{ind_2, ind_4, ind_7, ind_3, ind_9});
        criarJanela("Documental", new PnlDocumental());
    }//GEN-LAST:event_btnDocumentalMousePressed

    private void btnMateriaPrimaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMateriaPrimaMousePressed
        setColor(btnMateriaPrima);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btnConfig, btnCadastro, btnLaboratorio, btnDocumental, btnProdutoAcabado},
                new JPanel[]{ind_2, ind_4, ind_7, ind_8, ind_9});
        criarJanela("Matéria-Prima", new PnlMateriaPrima());
    }//GEN-LAST:event_btnMateriaPrimaMousePressed

    private void btnProdutoAcabadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoAcabadoMousePressed
        setColor(btnProdutoAcabado);
        ind_9.setOpaque(true);
        resetColor(new JPanel[]{btnConfig, btnCadastro, btnLaboratorio, btnDocumental, btnMateriaPrima},
                new JPanel[]{ind_2, ind_4, ind_7, ind_8, ind_3});
        criarJanela("Produto", new PnlProdutoAcabado());
    }//GEN-LAST:event_btnProdutoAcabadoMousePressed

    /**
     * Método para criar o Form FrmPrincipal()
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCadastro;
    private javax.swing.JPanel btnConfig;
    private javax.swing.JPanel btnDocumental;
    private javax.swing.JPanel btnLaboratorio;
    private javax.swing.JPanel btnMateriaPrima;
    private javax.swing.JToggleButton btnMenu;
    private javax.swing.JPanel btnProdutoAcabado;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_7;
    private javax.swing.JPanel ind_8;
    private javax.swing.JPanel ind_9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDashboard1;
    private javax.swing.JLabel lblLabMenuTop;
    private javax.swing.JLabel lblLimsMenuTop;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoMenuTop;
    private javax.swing.JPanel pnlTopMenu;
    private javax.swing.JPanel side_pane;
    private javax.swing.JTabbedPane tblPrincipal;
    // End of variables declaration//GEN-END:variables

    private void carregar() {
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(new Frames().getIcon());
        setTitle("Controle de Qualidade - Modulo CQ_Desktop - Usuário: " + System.getProperty("user"));

        lblLogoMenuTop.setVisible(false);
        lblLimsMenuTop.setVisible(false);
        lblLabMenuTop.setVisible(false);
        btnMenu.setSelected(true);

        if (btnLaboratorio.isVisible()) {
            setColor(btnLaboratorio);
            ind_7.setOpaque(true);
            resetColor(new JPanel[]{btnConfig, btnCadastro, btnDocumental}, new JPanel[]{ind_2, ind_4, ind_8});
            criarJanela("Laboratório", new PnlLaboratorio());
        }

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                logout();
            }
        });
    }

    private void logout() {
        int option = JOptionPane.showConfirmDialog(
                null,
                "Tem certeza de que deseja fechar o aplicativo?",
                "Confirmação de Fechamento",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            LoginDAO loginDAO = new LoginDAO();
            UsuarioDAO userDAO = new UsuarioDAO();
            try {
                Usuario user = new UsuarioDAO().findById(Usuario.class,
                        Long.parseLong(System.getProperty("user_id")));
                loginDAO.logoffUsuario(user);
                userDAO.atualizarLogoffUsuario(user);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao Gravar Logout" + ex);
            }
            System.exit(0);
        }
    }

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(23, 35, 51));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);
        }

    }

    private void menu() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (btnMenu.isSelected()) {
            //Ativa O Menu
            btnMenu.setSelected(true);
            btnMenu.setIcon(new ImageIcon(getClass().getResource("/Imagem/icon_menu_25_2.png")));
            lblLogoMenuTop.setVisible(false);
            lblLimsMenuTop.setVisible(false);
            lblLabMenuTop.setVisible(false);
            side_pane.setVisible(true);
            pnlTopMenu.setOpaque(true);
        } else {
            //Desativa O Menu
            btnMenu.setSelected(false);
            btnMenu.setIcon(new ImageIcon(getClass().getResource("/Imagem/icon_menu_25_1.png")));
            lblLogoMenuTop.setVisible(true);
            lblLimsMenuTop.setVisible(true);
            lblLabMenuTop.setVisible(true);
            side_pane.setVisible(false);
            pnlTopMenu.setOpaque(false);
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }

    public void criarJanela(String title, JPanel pnl) {
        ImageIcon icone = new ImageIcon(getClass().getResource("/Imagem/icon_cancel.png"));
        try {
            if (tblPrincipal.indexOfTab(title) == -1) {
                tblPrincipal.addTab(title, pnl);
                int index = tblPrincipal.indexOfTab(title);

                JPanel pnlTab = new JPanel(new GridBagLayout());
                pnlTab.setOpaque(false);
                JLabel lblTitle = new JLabel(title);
                JButton btnClose = new JButton();
                btnClose.setIcon(icone);
                btnClose.setContentAreaFilled(false);
                btnClose.setPreferredSize(new Dimension(25, 25));
                btnClose.setHorizontalTextPosition(SwingConstants.RIGHT);
                lblTitle.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 40));
                lblTitle.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 12));

                GridBagConstraints gbc = new GridBagConstraints();
                gbc.gridx = 0;
                gbc.gridy = 0;
                gbc.weightx = 1;

                pnlTab.add(lblTitle, gbc);

                gbc.gridx++;
                gbc.weightx = 0;
                pnlTab.add(btnClose, gbc);

                btnClose.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        int dialogResult = JOptionPane.showConfirmDialog(null,
                                "Deseja fechar essa janela?", "Aviso", JOptionPane.YES_NO_OPTION);
                        if (dialogResult == 0) {
                            int index = tblPrincipal.indexOfTab(title);
                            if (index >= 0) {
                                tblPrincipal.remove(index);
                                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                            }
                        }
                    }
                });
                btnClose.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent evt) {
                    }

                    @Override
                    public void mousePressed(MouseEvent evt) {
                    }

                    @Override
                    public void mouseReleased(MouseEvent evt) {
                    }

                    @Override
                    public void mouseEntered(MouseEvent evt) {
                        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                    }

                    @Override
                    public void mouseExited(MouseEvent evt) {
                        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    }
                });
                tblPrincipal.setTabComponentAt(index, pnlTab);
                tblPrincipal.setSelectedIndex(tblPrincipal.indexOfTab(title));
            } else {
                tblPrincipal.setSelectedIndex(tblPrincipal.indexOfTab(title));
            }
        } catch (Exception e) {

        }

    }

    private void checkTempoInatividade() {
        Long eventMask = AWTEvent.KEY_EVENT_MASK | AWTEvent.MOUSE_EVENT_MASK;
        Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {
            @Override
            public void eventDispatched(AWTEvent e) {
                timer = System.currentTimeMillis();
            }
        }, eventMask);
        timer = System.currentTimeMillis();
        new Thread(new Runnable() {
            @Override
            public void run() {
                Integer tempo;
                try {
                    tempo = new SegurancaDAO().findByTipo(Seguranca.FECHAR).getNumero();
                } catch (Exception ex) {
                    tempo = 120;
                }
                while (true) {
                    if (System.currentTimeMillis() - timer > tempo * 60000) {
                        System.exit(0);
                        break;
                    }
                }
            }
        }).start();
    }

    private void trocarSenha() {
        try {
            FrmSenhaAlterar frm = new FrmSenhaAlterar(null, true);
            frm.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Alterar Senha" + ex);
        }
    }

    private void dadosUsuario() {
        try {
            FrmUsuarioVisualizar frm = new FrmUsuarioVisualizar(null, true);
            frm.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Abrir" + ex);
        }

    }
}
