/*
 * Copyright (C) 2019 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.principal;

import br.com.lablims.util.AcessoSistema;
import br.com.lablims.util.Frames;
import br.com.lablims.util.MouseEventButton;
import br.com.lablims.view.cadastro.FrmAnalise;
import br.com.lablims.view.cadastro.FrmAnaliseStatus;
import br.com.lablims.view.cadastro.FrmAnaliseTipo;
import br.com.lablims.view.cadastro.FrmColuna;
import br.com.lablims.view.cadastro.FrmColunaConfig;
import br.com.lablims.view.cadastro.FrmEquipamento;
import br.com.lablims.view.cadastro.FrmMaterial;
import br.com.lablims.view.cadastro.FrmMetodologia;
import br.com.lablims.view.cadastro.FrmPlanoAnalise;
import br.com.lablims.view.cadastro.FrmReagente;
import java.awt.Cursor;

/**
 *
 * @author rafael.lopes
 */
public class PnlCadastro extends javax.swing.JPanel {

    /**
     * Creates new form PnlCadastro
     */
    public PnlCadastro() {
        initComponents();
        pnlMaterial.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmMaterial.class.getSimpleName())));
        pnlReagente.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmReagente.class.getSimpleName())));
        pnlMetodologia.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmMetodologia.class.getSimpleName())));
        pnlAnalise.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmAnalise.class.getSimpleName())));
        pnlTipoAnalise.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmAnaliseTipo.class.getSimpleName())));
        pnlAnaliseStatus.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmAnaliseStatus.class.getSimpleName())));
        pnlPlanoAnalise.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmPlanoAnalise.class.getSimpleName())));
        pnlColunas.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmColunaConfig.class.getSimpleName())));
        pnlEquipamentos.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmEquipamento.class.getSimpleName())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMaterial = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlReagente = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlMetodologia = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlTipoAnalise = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlAnalise = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlAnaliseStatus = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlPlanoAnalise = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMateriaPrima = new javax.swing.JLabel();
        lblMateriaPrima1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMateriaPrima2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlPadrao = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pnlColunas = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnlEquipamentos = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblMateriaPrima3 = new javax.swing.JLabel();

        pnlMaterial.setBackground(new java.awt.Color(255, 255, 255));
        pnlMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMaterialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMaterialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMaterialMouseExited(evt);
            }
        });
        pnlMaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_pilula.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMaterial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Material");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMaterial.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 20));

        pnlReagente.setBackground(new java.awt.Color(255, 255, 255));
        pnlReagente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlReagente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReagenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReagenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReagenteMouseExited(evt);
            }
        });
        pnlReagente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_solucao_32.png"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlReagente.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Reagentes");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlReagente.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, -1));

        pnlMetodologia.setBackground(new java.awt.Color(255, 255, 255));
        pnlMetodologia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMetodologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMetodologiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMetodologiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMetodologiaMouseExited(evt);
            }
        });
        pnlMetodologia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_metodologia.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMetodologia.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Metodologias");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMetodologia.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, -1));

        pnlTipoAnalise.setBackground(new java.awt.Color(255, 255, 255));
        pnlTipoAnalise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTipoAnalise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTipoAnaliseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlTipoAnaliseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTipoAnaliseMouseExited(evt);
            }
        });
        pnlTipoAnalise.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_anlise_tipo_32.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTipoAnalise.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Tipo de Análise");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTipoAnalise.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 20));

        pnlAnalise.setBackground(new java.awt.Color(255, 255, 255));
        pnlAnalise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAnalise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAnaliseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAnaliseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAnaliseMouseExited(evt);
            }
        });
        pnlAnalise.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_tubo_ensaio_32.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAnalise.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Análise");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAnalise.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 20));

        pnlAnaliseStatus.setBackground(new java.awt.Color(255, 255, 255));
        pnlAnaliseStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAnaliseStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAnaliseStatusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAnaliseStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAnaliseStatusMouseExited(evt);
            }
        });
        pnlAnaliseStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_status_32.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAnaliseStatus.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Status de");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAnaliseStatus.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 20));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Análise");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAnaliseStatus.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 70, 20));

        pnlPlanoAnalise.setBackground(new java.awt.Color(255, 255, 255));
        pnlPlanoAnalise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPlanoAnalise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPlanoAnaliseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPlanoAnaliseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPlanoAnaliseMouseExited(evt);
            }
        });
        pnlPlanoAnalise.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_analise_32.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPlanoAnalise.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Plano de");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPlanoAnalise.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 20));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Análise");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPlanoAnalise.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 60, 20));

        lblMateriaPrima.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMateriaPrima.setText("Produtos");

        lblMateriaPrima1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMateriaPrima1.setText("Materiais");

        lblMateriaPrima2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMateriaPrima2.setText("Análises");

        pnlPadrao.setBackground(new java.awt.Color(255, 255, 255));
        pnlPadrao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPadrao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPadraoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPadraoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPadraoMouseExited(evt);
            }
        });
        pnlPadrao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_padrao_32.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPadrao.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Padrões");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPadrao.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, -1));

        pnlColunas.setBackground(new java.awt.Color(255, 255, 255));
        pnlColunas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlColunas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlColunasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlColunasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlColunasMouseExited(evt);
            }
        });
        pnlColunas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_hplc_column.jpg"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlColunas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Colunas");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlColunas.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, -1));

        pnlEquipamentos.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEquipamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEquipamentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlEquipamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlEquipamentosMouseExited(evt);
            }
        });
        pnlEquipamentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_sistema.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEquipamentos.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Equipamentos");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEquipamentos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, 30));

        lblMateriaPrima3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMateriaPrima3.setText("Equipamentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMateriaPrima1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlReagente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlColunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMateriaPrima2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlTipoAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlAnaliseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMateriaPrima)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlPlanoAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMateriaPrima3)
                            .addComponent(pnlEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(208, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMateriaPrima1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlReagente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMateriaPrima2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTipoAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAnaliseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMateriaPrima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPlanoAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMateriaPrima3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMaterialMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmMaterial.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlMaterialMouseClicked
    private void pnlMaterialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMaterialMouseEntered
        MouseEventButton.setMouseEntered(pnlMaterial);
    }//GEN-LAST:event_pnlMaterialMouseEntered

    private void pnlMaterialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMaterialMouseExited
        MouseEventButton.setMouseExited(pnlMaterial);
    }//GEN-LAST:event_pnlMaterialMouseExited

    private void pnlMetodologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMetodologiaMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmMetodologia.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlMetodologiaMouseClicked

    private void pnlMetodologiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMetodologiaMouseEntered
        MouseEventButton.setMouseEntered(pnlMetodologia);
    }//GEN-LAST:event_pnlMetodologiaMouseEntered

    private void pnlMetodologiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMetodologiaMouseExited
        MouseEventButton.setMouseExited(pnlMetodologia);
    }//GEN-LAST:event_pnlMetodologiaMouseExited

    private void pnlTipoAnaliseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTipoAnaliseMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmAnaliseTipo.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlTipoAnaliseMouseClicked

    private void pnlTipoAnaliseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTipoAnaliseMouseEntered
        MouseEventButton.setMouseEntered(pnlTipoAnalise);
    }//GEN-LAST:event_pnlTipoAnaliseMouseEntered

    private void pnlTipoAnaliseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTipoAnaliseMouseExited
        MouseEventButton.setMouseExited(pnlTipoAnalise);
    }//GEN-LAST:event_pnlTipoAnaliseMouseExited

    private void pnlAnaliseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnaliseMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmAnalise.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlAnaliseMouseClicked

    private void pnlAnaliseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnaliseMouseEntered
        MouseEventButton.setMouseEntered(pnlAnalise);
    }//GEN-LAST:event_pnlAnaliseMouseEntered

    private void pnlAnaliseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnaliseMouseExited
        MouseEventButton.setMouseExited(pnlAnalise);
    }//GEN-LAST:event_pnlAnaliseMouseExited

    private void pnlPlanoAnaliseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPlanoAnaliseMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmPlanoAnalise.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlPlanoAnaliseMouseClicked

    private void pnlPlanoAnaliseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPlanoAnaliseMouseEntered
        MouseEventButton.setMouseEntered(pnlPlanoAnalise);
    }//GEN-LAST:event_pnlPlanoAnaliseMouseEntered

    private void pnlPlanoAnaliseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPlanoAnaliseMouseExited
        MouseEventButton.setMouseExited(pnlPlanoAnalise);
    }//GEN-LAST:event_pnlPlanoAnaliseMouseExited

    private void pnlAnaliseStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnaliseStatusMouseEntered
       MouseEventButton.setMouseEntered(pnlAnaliseStatus);
    }//GEN-LAST:event_pnlAnaliseStatusMouseEntered

    private void pnlAnaliseStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnaliseStatusMouseExited
        MouseEventButton.setMouseExited(pnlAnaliseStatus);
    }//GEN-LAST:event_pnlAnaliseStatusMouseExited

    private void pnlAnaliseStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnaliseStatusMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmAnaliseStatus.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlAnaliseStatusMouseClicked

    private void pnlReagenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReagenteMouseClicked
       setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmReagente.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlReagenteMouseClicked

    private void pnlReagenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReagenteMouseEntered
       MouseEventButton.setMouseEntered(pnlReagente);
    }//GEN-LAST:event_pnlReagenteMouseEntered

    private void pnlReagenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReagenteMouseExited
       MouseEventButton.setMouseExited(pnlReagente);
    }//GEN-LAST:event_pnlReagenteMouseExited

    private void pnlPadraoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPadraoMouseExited
        MouseEventButton.setMouseExited(pnlPadrao);
    }//GEN-LAST:event_pnlPadraoMouseExited

    private void pnlPadraoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPadraoMouseEntered
        MouseEventButton.setMouseEntered(pnlPadrao);
    }//GEN-LAST:event_pnlPadraoMouseEntered

    private void pnlPadraoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPadraoMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //Frames.carregarJFrame(FrmP.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlPadraoMouseClicked

    private void pnlColunasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunasMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmColuna.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlColunasMouseClicked

    private void pnlColunasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunasMouseEntered
        MouseEventButton.setMouseEntered(pnlColunas);
    }//GEN-LAST:event_pnlColunasMouseEntered

    private void pnlColunasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlColunasMouseExited
        MouseEventButton.setMouseExited(pnlColunas);
    }//GEN-LAST:event_pnlColunasMouseExited

    private void pnlEquipamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEquipamentosMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmEquipamento.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlEquipamentosMouseClicked

    private void pnlEquipamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEquipamentosMouseEntered
        MouseEventButton.setMouseEntered(pnlEquipamentos);
    }//GEN-LAST:event_pnlEquipamentosMouseEntered

    private void pnlEquipamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEquipamentosMouseExited
        MouseEventButton.setMouseExited(pnlEquipamentos);
    }//GEN-LAST:event_pnlEquipamentosMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblMateriaPrima;
    private javax.swing.JLabel lblMateriaPrima1;
    private javax.swing.JLabel lblMateriaPrima2;
    private javax.swing.JLabel lblMateriaPrima3;
    private javax.swing.JPanel pnlAnalise;
    private javax.swing.JPanel pnlAnaliseStatus;
    private javax.swing.JPanel pnlColunas;
    private javax.swing.JPanel pnlEquipamentos;
    private javax.swing.JPanel pnlMaterial;
    private javax.swing.JPanel pnlMetodologia;
    private javax.swing.JPanel pnlPadrao;
    private javax.swing.JPanel pnlPlanoAnalise;
    private javax.swing.JPanel pnlReagente;
    private javax.swing.JPanel pnlTipoAnalise;
    // End of variables declaration//GEN-END:variables
}
