/*
 * Copyright (C) 2019 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.principal;

import br.com.lablims.util.AcessoSistema;
import br.com.lablims.util.Frames;
import br.com.lablims.util.MouseEventButton;
import br.com.lablims.view.config.FrmDepartamento;
import br.com.lablims.view.config.FrmGrupo;
import br.com.lablims.view.config.FrmSetor;
import br.com.lablims.view.config.FrmSistemaConfig;
import br.com.lablims.view.config.FrmUsuario;
import java.awt.Cursor;

/**
 *
 * @author rafael.lopes
 */
public class PnlConfigurar extends javax.swing.JPanel {

    /**
     * Creates new form PnlConfigurar
     */
    public PnlConfigurar() {
        initComponents();
        pnlUsuarios.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmUsuario.class.getSimpleName())));
        pnlGrupos.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmGrupo.class.getSimpleName())));
        pnlDepartamentos.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmDepartamento.class.getSimpleName())));
        pnlSetores.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmSetor.class.getSimpleName())));
        pnlSeguranca.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmSistemaConfig.class.getSimpleName())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsuarios = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlGrupos = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnlDepartamentos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlSetores = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlSeguranca = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMateriaPrima1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblMateriaPrima2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblMateriaPrima3 = new javax.swing.JLabel();

        pnlUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlUsuariosMouseExited(evt);
            }
        });
        pnlUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_usuario.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlUsuarios.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Usuários");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlUsuarios.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 20));

        pnlGrupos.setBackground(new java.awt.Color(255, 255, 255));
        pnlGrupos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGruposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGruposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGruposMouseExited(evt);
            }
        });
        pnlGrupos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_grupo.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlGrupos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Grupos");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlGrupos.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 20));

        pnlDepartamentos.setBackground(new java.awt.Color(255, 255, 255));
        pnlDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDepartamentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDepartamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDepartamentosMouseExited(evt);
            }
        });
        pnlDepartamentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_departamento_32.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDepartamentos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Departamentos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDepartamentos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 20));

        pnlSetores.setBackground(new java.awt.Color(255, 255, 255));
        pnlSetores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSetores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSetoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSetoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSetoresMouseExited(evt);
            }
        });
        pnlSetores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_setor_32.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSetores.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Setores");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSetores.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 20));

        pnlSeguranca.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeguranca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSeguranca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSegurancaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSegurancaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSegurancaMouseExited(evt);
            }
        });
        pnlSeguranca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_seguranca.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSeguranca.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Segurança");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSeguranca.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, -1));

        lblMateriaPrima1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMateriaPrima1.setText("Acesso");

        lblMateriaPrima2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMateriaPrima2.setText("Organização");

        lblMateriaPrima3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMateriaPrima3.setText("Política de Segurança");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMateriaPrima2)
                            .addComponent(lblMateriaPrima3)
                            .addComponent(lblMateriaPrima1)
                            .addComponent(pnlSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlSetores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(pnlGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 326, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMateriaPrima1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMateriaPrima2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDepartamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSetores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMateriaPrima3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuariosMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmUsuario.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlUsuariosMouseClicked

    private void pnlGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGruposMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmGrupo.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlGruposMouseClicked
    private void pnlDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDepartamentosMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmDepartamento.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlDepartamentosMouseClicked
    private void pnlSetoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSetoresMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmSetor.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlSetoresMouseClicked
    private void pnlSegurancaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSegurancaMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FrmSistemaConfig frm = new FrmSistemaConfig(null, true);
        frm.setVisible(true);
        frm.toFront();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlSegurancaMouseClicked

    private void pnlUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuariosMouseEntered
        MouseEventButton.setMouseEntered(pnlUsuarios);
    }//GEN-LAST:event_pnlUsuariosMouseEntered

    private void pnlUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuariosMouseExited
        MouseEventButton.setMouseExited(pnlUsuarios);
    }//GEN-LAST:event_pnlUsuariosMouseExited

    private void pnlGruposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGruposMouseEntered
        MouseEventButton.setMouseEntered(pnlGrupos);
    }//GEN-LAST:event_pnlGruposMouseEntered

    private void pnlGruposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGruposMouseExited
        MouseEventButton.setMouseExited(pnlGrupos);
    }//GEN-LAST:event_pnlGruposMouseExited

    private void pnlDepartamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDepartamentosMouseEntered
        MouseEventButton.setMouseEntered(pnlDepartamentos);
    }//GEN-LAST:event_pnlDepartamentosMouseEntered

    private void pnlDepartamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDepartamentosMouseExited
        MouseEventButton.setMouseExited(pnlDepartamentos);
    }//GEN-LAST:event_pnlDepartamentosMouseExited

    private void pnlSetoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSetoresMouseEntered
        MouseEventButton.setMouseEntered(pnlSetores);
    }//GEN-LAST:event_pnlSetoresMouseEntered

    private void pnlSetoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSetoresMouseExited
        MouseEventButton.setMouseExited(pnlSetores);
    }//GEN-LAST:event_pnlSetoresMouseExited

    private void pnlSegurancaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSegurancaMouseEntered
        MouseEventButton.setMouseEntered(pnlSeguranca);
    }//GEN-LAST:event_pnlSegurancaMouseEntered

    private void pnlSegurancaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSegurancaMouseExited
        MouseEventButton.setMouseExited(pnlSeguranca);
    }//GEN-LAST:event_pnlSegurancaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblMateriaPrima1;
    private javax.swing.JLabel lblMateriaPrima2;
    private javax.swing.JLabel lblMateriaPrima3;
    private javax.swing.JPanel pnlDepartamentos;
    private javax.swing.JPanel pnlGrupos;
    private javax.swing.JPanel pnlSeguranca;
    private javax.swing.JPanel pnlSetores;
    private javax.swing.JPanel pnlUsuarios;
    // End of variables declaration//GEN-END:variables

}
