/*
 * Copyright (C) 2019 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.principal;

import br.com.lablims.util.AcessoSistema;
import br.com.lablims.util.Frames;
import br.com.lablims.util.MouseEventButton;
import br.com.lablims.view.documental.FrmDocumentos;
import br.com.lablims.view.documental.FrmLiberarLoteMateriaPrima;
import java.awt.Cursor;

/**
 *
 * @author rafael.lopes
 */
public class PnlDocumental extends javax.swing.JPanel {

    /**
     * Creates new form PnlConfigurar
     */
    public PnlDocumental() {
        initComponents();
        pnlLiberarLotesMp.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmLiberarLoteMateriaPrima.class.getSimpleName())));
        pnlDocumentos.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmDocumentos.class.getSimpleName())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMateriaPrima1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlLiberarLotesMp = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblMateriaPrima2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlDocumentos = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        lblMateriaPrima1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMateriaPrima1.setText("Matéria-Prima");

        pnlLiberarLotesMp.setBackground(new java.awt.Color(255, 255, 255));
        pnlLiberarLotesMp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLiberarLotesMp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLiberarLotesMpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLiberarLotesMpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLiberarLotesMpMouseExited(evt);
            }
        });
        pnlLiberarLotesMp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_finish_32.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLiberarLotesMp.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Lotes MP");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLiberarLotesMp.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, 20));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Liberação de");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLiberarLotesMp.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 6, 110, -1));

        lblMateriaPrima2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMateriaPrima2.setText("Documentos");

        pnlDocumentos.setBackground(new java.awt.Color(255, 255, 255));
        pnlDocumentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDocumentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDocumentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDocumentosMouseExited(evt);
            }
        });
        pnlDocumentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_scanner_32.png"))); // NOI18N
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Digitalizados");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, -1));

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Documentos");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 6, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblMateriaPrima1)
                                .addGap(0, 662, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(604, 604, 604))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlLiberarLotesMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMateriaPrima2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMateriaPrima1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLiberarLotesMp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMateriaPrima2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlLiberarLotesMpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLiberarLotesMpMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmLiberarLoteMateriaPrima.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlLiberarLotesMpMouseClicked

    private void pnlLiberarLotesMpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLiberarLotesMpMouseEntered
        MouseEventButton.setMouseEntered(pnlLiberarLotesMp);
    }//GEN-LAST:event_pnlLiberarLotesMpMouseEntered

    private void pnlLiberarLotesMpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLiberarLotesMpMouseExited
        MouseEventButton.setMouseExited(pnlLiberarLotesMp);
    }//GEN-LAST:event_pnlLiberarLotesMpMouseExited

    private void pnlDocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentosMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmDocumentos.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlDocumentosMouseClicked

    private void pnlDocumentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentosMouseEntered
        MouseEventButton.setMouseEntered(pnlDocumentos);
    }//GEN-LAST:event_pnlDocumentosMouseEntered

    private void pnlDocumentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentosMouseExited
         MouseEventButton.setMouseExited(pnlDocumentos);
    }//GEN-LAST:event_pnlDocumentosMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblMateriaPrima1;
    private javax.swing.JLabel lblMateriaPrima2;
    private javax.swing.JPanel pnlDocumentos;
    private javax.swing.JPanel pnlLiberarLotesMp;
    // End of variables declaration//GEN-END:variables

}
