package br.com.lablims.view.cadastro;

import br.com.lablims.dao.MaterialDAO;
import javax.swing.JOptionPane;
import br.com.lablims.dao.MetodologiaDAO;
import br.com.lablims.model.Material;
import br.com.lablims.model.Metodologia;
import br.com.lablims.util.Senha;
import br.com.lablims.util.DataHora;
import br.com.lablims.util.FieldFormatLimit;
import br.com.lablims.util.Frames;
import br.com.lablims.util.TableSorter;
import java.awt.Cursor;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael.lopes
 */
public class FrmMetodologiaDadosRas extends javax.swing.JDialog {

    private Metodologia metodo;

    /**
     * Creates new form FrmConfigAcesso
     *
     * @param parent
     * @param modal
     */
    public FrmMetodologiaDadosRas(java.awt.Frame parent, boolean modal, Metodologia mtd) {
        super(parent, modal);
        initComponents();
        Frames.setUpFrame(this, "Registro de Analise", true);
//        metodo = mtd;
//        limparCampos();
//        pnlRas.setVisible(false);
//        txtCodMetodo.setEditable(false);
//        carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        pnlRas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAcompanhamento = new javax.swing.JTable();
        btnAdicionarLote1 = new javax.swing.JButton();
        btnRemoverLote1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        pnlMetodo = new javax.swing.JPanel();
        txtCodMetodo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMetodo = new javax.swing.JTextField();
        txtVersao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCancelar.setText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlRas.setBorder(javax.swing.BorderFactory.createTitledBorder("RA's"));

        jScrollPane3.setEnabled(false);

        tblAcompanhamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Documento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblAcompanhamento);

        btnAdicionarLote1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_plus_24.png"))); // NOI18N
        btnAdicionarLote1.setEnabled(false);
        btnAdicionarLote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarLote1ActionPerformed(evt);
            }
        });

        btnRemoverLote1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_minus_24.png"))); // NOI18N
        btnRemoverLote1.setEnabled(false);
        btnRemoverLote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverLote1ActionPerformed(evt);
            }
        });

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_edit.png"))); // NOI18N
        btnEditar1.setEnabled(false);
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRasLayout = new javax.swing.GroupLayout(pnlRas);
        pnlRas.setLayout(pnlRasLayout);
        pnlRasLayout.setHorizontalGroup(
            pnlRasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRasLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoverLote1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarLote1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRasLayout.setVerticalGroup(
            pnlRasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRasLayout.createSequentialGroup()
                .addComponent(btnAdicionarLote1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoverLote1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pnlMetodo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtCodMetodo.setEditable(false);
        txtCodMetodo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Versão");

        jLabel5.setText("Método:");

        txtMetodo.setEditable(false);
        txtMetodo.setBackground(new java.awt.Color(204, 204, 204));

        txtVersao.setEditable(false);
        txtVersao.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlMetodoLayout = new javax.swing.GroupLayout(pnlMetodo);
        pnlMetodo.setLayout(pnlMetodoLayout);
        pnlMetodoLayout.setHorizontalGroup(
            pnlMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMetodoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMetodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMetodoLayout.setVerticalGroup(
            pnlMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMetodoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMetodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAdicionarLote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarLote1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarLote1ActionPerformed

    private void btnRemoverLote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverLote1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverLote1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMetodologiaDadosRas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmMetodologiaDadosRas dialog = new FrmMetodologiaDadosRas(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarLote1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnRemoverLote1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlMetodo;
    private javax.swing.JPanel pnlRas;
    private javax.swing.JTable tblAcompanhamento;
    private javax.swing.JTextField txtCodMetodo;
    private javax.swing.JTextField txtMetodo;
    private javax.swing.JTextField txtVersao;
    // End of variables declaration//GEN-END:variables

//    public final void readMateriais() {
//        DefaultTableModel model = (DefaultTableModel) tblMaterial.getModel();
//        MaterialDAO materialDAO = new MaterialDAO();
//        model.setNumRows(0);
//        try {
//            for (Material material : materialDAO.findMaterialByMetodologia(metodo.getId())) {
//                model.addRow(new Object[]{
//                    material.getId(),
//                    material.getCodMaterial(),
//                    material.getMaterial(),
//                    material.getTipo(),
//                    material.getVersion()
//                });
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
//        }
//    }
//
//    private void atulizarMetodologia() {
//        MetodologiaDAO mtdDAO = new MetodologiaDAO();
//        try {
//            metodo.setVersao((Integer) txtVersao.getValue());
//            metodo.setMetodo(txtMetodo.getText().trim().toUpperCase());
//            metodo.setCategoria(txtCategoria.getText().trim().toUpperCase());
//            metodo.setLink(txtLink.getText().trim().toLowerCase());
//            metodo.setVersion(metodo.getVersion() + 1);
//            mtdDAO.salvar(metodo);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao atualizar dados: " + e);
//        }
//    }
//
//    private void carregarDados() {
//        try {
//            txtCodMetodo.setText(metodo.getCodMetodo().toUpperCase());
//            txtVersao.setValue(metodo.getVersao());
//            txtMetodo.setText(metodo.getMetodo().toUpperCase());
//            txtCategoria.setText(metodo.getCategoria().toUpperCase());
//            txtLink.setText(metodo.getLink());
//            readMateriais();
//            carregarAuditoria();
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + ex);
//        }
//    }
//
//    private void limparCampos() {
//        txtCodMetodo.setDocument(new FieldFormatLimit(14, FieldFormatLimit.LETRAS_NUMEROS_MAIUSCULO));
//        txtCodMetodo.setText(null);
//        txtMetodo.setText(null);
//        txtCategoria.setText(null);
//        txtLink.setText(null);
//        txtVersao.setModel(new SpinnerNumberModel(0, 0, 50, 1));
//    }
//
//    private void addMaterial(Material mat) {
//        MetodologiaDAO mtdDAO = new MetodologiaDAO();
//        try {
//            Metodologia mtd = mtdDAO.findMetodoWithMaterial(metodo.getId());
//            mtd.getMaterial().add(mat);
//            mtd.setVersion(mtd.getVersion() + 1);
//            mtdDAO.salvar(mtd);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao atualizar Material: " + e);
//        } finally {
//            carregarAuditoria();
//        }
//    }
//
//    private void removerMaterial(Material mat) {
//        MetodologiaDAO mtdDAO = new MetodologiaDAO();
//        try {
//            Metodologia mtd = mtdDAO.findMetodoWithMaterial(metodo.getId());
//            mtd.getMaterial().remove(mat);
//            mtd.setVersion(mtd.getVersion() + 1);
//            mtdDAO.salvar(mtd);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao atualizar Material: " + e);
//        } finally {
//            carregarAuditoria();
//        }
//    }
//
//    private void carregarAuditoria() {
//        DefaultTableModel model = (DefaultTableModel) tblMateriaisAuditoria.getModel();
//        MetodologiaDAO mtdDAO = new MetodologiaDAO();
//        model.setNumRows(0);
//        try {
//            for (Metodologia mtd : mtdDAO.readMetodologiaMaterialAuditoria(metodo.getId())) {
//                model.addRow(new Object[]{
//                    mtd.getMaterial().stream().findFirst().get().getId(),
//                    mtd.getAudit().getMOD() == 0 ? "Criado" : (mtd.getAudit().getMOD() == 1 ? "Modificado" : "Removido"),
//                    mtd.getAudit().getComputador() + " / " + mtd.getAudit().getUserComputador(),
//                    mtd.getAudit().getUltimaModificacaoPor(),
//                    DataHora.getStringDateTime(mtd.getAudit().getUltimaModificacao()),
//                    mtd.getAudit().getMotivo()
//                });
//            }
//        } catch (Exception e) {
//        }
//    }
//
//    private void fechar() {
//        Frames.fecharFrame(this);
//    }
}
