/*
 * Copyright (C) 2019 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.cadastro;

import br.com.lablims.dao.PlanoAnaliseDAO;
import br.com.lablims.model.PlanoAnalise;
import br.com.lablims.util.AcessoSistema;
import br.com.lablims.util.DataHora;
import br.com.lablims.util.Frames;
import br.com.lablims.util.TableSorter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael.lopes
 */
public class FrmPlanoAnalise extends javax.swing.JFrame {

    private String ACESSO = new AcessoSistema().getAcessoSistema(this);

    /**
     * Creates new form FrmMetodologiaAnalise
     */
    public FrmPlanoAnalise() {
        initComponents();
        Frames.setUpFrame(this, "Planos de Analises", false);
        readMetodologiaAnalise();
        btnEditar.setEnabled(AcessoSistema.editarDados(ACESSO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblPaneMetodologia = new javax.swing.JTabbedPane();
        pnlMetodologia = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMetodologia = new javax.swing.JTable();
        txtPesquisarMetodologia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAtualizar = new javax.swing.JButton();
        pnlDados = new javax.swing.JPanel();
        pnlAuditoriaGrupos = new javax.swing.JPanel();
        txtPesquisarAuditoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMetodologiaAnaliseAuditoria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Metodologias"));

        tblMetodologia.setAutoCreateRowSorter(true);
        tblMetodologia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Metodologia_Id", "Método", "Versão", "Analises"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMetodologia.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblMetodologia.setSurrendersFocusOnKeystroke(true);
        tblMetodologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMetodologiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMetodologia);
        if (tblMetodologia.getColumnModel().getColumnCount() > 0) {
            tblMetodologia.getColumnModel().getColumn(0).setMinWidth(100);
            tblMetodologia.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblMetodologia.getColumnModel().getColumn(0).setMaxWidth(100);
            tblMetodologia.getColumnModel().getColumn(2).setMinWidth(80);
            tblMetodologia.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblMetodologia.getColumnModel().getColumn(2).setMaxWidth(80);
            tblMetodologia.getColumnModel().getColumn(3).setMinWidth(100);
            tblMetodologia.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblMetodologia.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        txtPesquisarMetodologia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarMetodologiaKeyReleased(evt);
            }
        });

        jLabel4.setText("Pesquisar:");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);
        jToolBar1.add(jSeparator1);

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_atualizar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setFocusable(false);
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizar.setPreferredSize(new java.awt.Dimension(60, 60));
        btnAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAtualizar);

        javax.swing.GroupLayout pnlMetodologiaLayout = new javax.swing.GroupLayout(pnlMetodologia);
        pnlMetodologia.setLayout(pnlMetodologiaLayout);
        pnlMetodologiaLayout.setHorizontalGroup(
            pnlMetodologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMetodologiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMetodologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMetodologiaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarMetodologia))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMetodologiaLayout.setVerticalGroup(
            pnlMetodologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMetodologiaLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMetodologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblPaneMetodologia.addTab("Análises por Metodologias", pnlMetodologia);

        pnlDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPesquisarAuditoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarAuditoriaKeyReleased(evt);
            }
        });

        jLabel5.setText("Pesquisar:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Auditoria de Análises por Métodologia"));

        tblMetodologiaAnaliseAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod_Analise_Id", "Versão", "MOD", "Metodologia_Id", "Descrição", "Descrição_MOD", "Analise_Id", "Analise_MOD", "Analise_Tipo_Id", "Analise_Tipo_MOD", "Setor_Id", "Setor_MOD", "Tempo_Min", "Tempo_Min_MOD", "Tempo_Médio", "Tempo_Medio_MOD", "Tempo_Max", "Tempo_Max_MOD", "Computador / AD_User ", "Usuario", "Data Modificação", "Motivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMetodologiaAnaliseAuditoria.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblMetodologiaAnaliseAuditoria);
        if (tblMetodologiaAnaliseAuditoria.getColumnModel().getColumnCount() > 0) {
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(0).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(1).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(2).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(3).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(4).setMinWidth(400);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(4).setPreferredWidth(400);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(5).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(6).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(7).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(8).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(8).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(9).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(9).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(10).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(10).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(11).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(11).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(12).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(12).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(14).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(14).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(15).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(15).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(16).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(16).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(17).setMinWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(17).setPreferredWidth(100);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(18).setMinWidth(120);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(18).setPreferredWidth(120);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(19).setMinWidth(150);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(19).setPreferredWidth(150);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(20).setMinWidth(120);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(20).setPreferredWidth(120);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(21).setMinWidth(500);
            tblMetodologiaAnaliseAuditoria.getColumnModel().getColumn(21).setPreferredWidth(500);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlAuditoriaGruposLayout = new javax.swing.GroupLayout(pnlAuditoriaGrupos);
        pnlAuditoriaGrupos.setLayout(pnlAuditoriaGruposLayout);
        pnlAuditoriaGruposLayout.setHorizontalGroup(
            pnlAuditoriaGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAuditoriaGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisarAuditoria)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAuditoriaGruposLayout.setVerticalGroup(
            pnlAuditoriaGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuditoriaGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAuditoriaGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAuditoriaGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAuditoriaGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblPaneMetodologia.addTab("Audit Trail", pnlDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblPaneMetodologia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblPaneMetodologia)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMetodologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMetodologiaMouseClicked
        if (evt.getClickCount() == 2) {
            atualizar();
        }
    }//GEN-LAST:event_tblMetodologiaMouseClicked

    private void txtPesquisarMetodologiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarMetodologiaKeyReleased
        TableSorter.TableSorter(tblMetodologia, txtPesquisarMetodologia);
    }//GEN-LAST:event_txtPesquisarMetodologiaKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblMetodologia.getSelectedRow() != -1) {
            atualizar();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtPesquisarAuditoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarAuditoriaKeyReleased
        TableSorter.TableSorter(tblMetodologiaAnaliseAuditoria, txtPesquisarAuditoria);
    }//GEN-LAST:event_txtPesquisarAuditoriaKeyReleased

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        readMetodologiaAnalise();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPlanoAnalise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPlanoAnalise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPlanoAnalise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPlanoAnalise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmPlanoAnalise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    public static javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlAuditoriaGrupos;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlMetodologia;
    private javax.swing.JTable tblMetodologia;
    private javax.swing.JTable tblMetodologiaAnaliseAuditoria;
    private javax.swing.JTabbedPane tblPaneMetodologia;
    private javax.swing.JTextField txtPesquisarAuditoria;
    private javax.swing.JTextField txtPesquisarMetodologia;
    // End of variables declaration//GEN-END:variables

    public final void readMetodologiaAnalise() {
        DefaultTableModel model = (DefaultTableModel) tblMetodologia.getModel();
        PlanoAnaliseDAO paDAO = new PlanoAnaliseDAO();
        model.setNumRows(0);
        try {
            for (Object[] objects : paDAO.readMetodosPlanosAnalises()) {
                model.addRow(new Object[]{
                    (Integer) objects[0],
                    objects[1].toString() + " - " + objects[2].toString(),
                    (Integer) objects[3],
                    (Integer) objects[4]
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
        } finally {
            carregarAuditoria();
        }
    }

    private void atualizar() {
        if (AcessoSistema.editarDados(ACESSO)) {
            try {
                new FrmPlanoAnaliseConfig(null, false,
                        new Long((Integer) tblMetodologia.getValueAt(tblMetodologia.getSelectedRow(), 0)))
                        .setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
            } finally {
                carregarAuditoria();
            }
        }
    }

    private void carregarAuditoria() {
        DefaultTableModel model = (DefaultTableModel) tblMetodologiaAnaliseAuditoria.getModel();
        PlanoAnaliseDAO mtdAnaliseDAO = new PlanoAnaliseDAO();
        model.setNumRows(0);
        try {
            for (PlanoAnalise mtdAnalise : mtdAnaliseDAO.readPlanoAnaliseAuditoria()) {
                model.addRow(new Object[]{
                    mtdAnalise.getId(),
                    mtdAnalise.getVersion(),
                    mtdAnalise.getAudit().getMOD() == 0 ? "Criado"
                    : (mtdAnalise.getAudit().getMOD() == 1 ? "Modificado" : "Removido"),
                    mtdAnalise.getMetodologia().getId(),
                    mtdAnalise.getDescricao(),
                    mtdAnalise.getDescricao_MOD() == false ? "Não Alterado" : "Alterado",
                    mtdAnalise.getAnalise().getId(),
                    mtdAnalise.getAnalise_MOD() == false ? "Não Alterado" : "Alterado",
                    mtdAnalise.getAnaliseTipo().getId(),
                    mtdAnalise.getAnalise_MOD() == false ? "Não Alterado" : "Alterado",
                    mtdAnalise.getSetor().getId(),
                    mtdAnalise.getSetor_MOD() == false ? "Não Alterado" : "Alterado",
                    mtdAnalise.getLeadTimeMin(),
                    mtdAnalise.getLeadTimeMin_MOD() == false ? "Não Alterado" : "Alterado",
                    mtdAnalise.getLeadTimeMedio(),
                    mtdAnalise.getLeadTimeMedio_MOD() == false ? "Não Alterado" : "Alterado",
                    mtdAnalise.getLeadTimeMax(),
                    mtdAnalise.getLeadTimeMax_MOD() == false ? "Não Alterado" : "Alterado",
                    mtdAnalise.getAudit().getComputador() + " / " + mtdAnalise.getAudit().getUserComputador(),
                    mtdAnalise.getAudit().getUltimaModificacaoPor(),
                    DataHora.getStringDateTime(mtdAnalise.getAudit().getUltimaModificacao()),
                    mtdAnalise.getAudit().getMotivo()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados de Auditoria: " + e);
        }
    }
}
