/*
 * Copyright (C) 2019 rafael.lopes
 *
 * Este programa é um software livre: você pode redistribuí-lo e / ou modificar
 * sob os termos da GNU General Public License, conforme publicado pela
 * a Free Software Foundation, seja a versão 3 da Licença, quanto
 * qualquer versão posterior.
 *
 * Este programa é distribuído na esperança de que seja útil,
 * mas SEM QUALQUER GARANTIA; sem a garantia implícita de
 * COMERCIALIZAÇÃO OU APTIDÃO PARA UM PROPÓSITO PARTICULAR. Veja o
 * GNU General Public License para obter mais detalhes.
 *
 * Você deve ter recebido uma cópia da GNU General Public License
 *  juntamente com este programa. Caso contrário, veja <http://www.gnu.org/licenses/>.
 */
package br.com.lablims.view.cadastro;


import br.com.lablims.dao.PlanoAnaliseDAO;
import br.com.lablims.dao.MetodologiaDAO;

import br.com.lablims.model.Metodologia;
import br.com.lablims.model.PlanoAnalise;
import br.com.lablims.util.AcessoSistema;
import br.com.lablims.util.Senha;
import br.com.lablims.util.Frames;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael.lopes
 */
public class FrmPlanoAnaliseConfig extends javax.swing.JDialog {

    private String ACESSO = new AcessoSistema().getAcessoSistema(this);
    private Long metodo_id;

    /**
     * Creates new form FrmMetodologiaAnaliseDados
     */
    public FrmPlanoAnaliseConfig(java.awt.Frame parent, boolean modal, Long mtd_id) {
        super(parent, modal);
        metodo_id = mtd_id;
        initComponents();
        Frames.setUpFrame(this, "Plano de Análise", false);
        readPlanoAnalise();
        btnAdicionar.setEnabled(AcessoSistema.criarDados(ACESSO));
        btnRemover.setEnabled(AcessoSistema.deletarDados(ACESSO));
        btnEditar.setEnabled(AcessoSistema.editarDados(ACESSO));
        btnReagente.setEnabled(AcessoSistema.editarDados(ACESSO));
        btnPadrao.setEnabled(AcessoSistema.editarDados(ACESSO));
        btnColuna.setEnabled(AcessoSistema.editarDados(ACESSO));
        btnSolucaoReagente.setEnabled(AcessoSistema.editarDados(ACESSO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlMetodo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMetodo = new javax.swing.JTextField();
        txtVersao = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPlanoAnalise = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnReagente = new javax.swing.JButton();
        btnPadrao = new javax.swing.JButton();
        btnColuna = new javax.swing.JButton();
        btnSolucaoReagente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMetodo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Versão");

        jLabel5.setText("Método:");

        txtMetodo.setEditable(false);

        txtVersao.setEditable(false);

        javax.swing.GroupLayout pnlMetodoLayout = new javax.swing.GroupLayout(pnlMetodo);
        pnlMetodo.setLayout(pnlMetodoLayout);
        pnlMetodoLayout.setHorizontalGroup(
            pnlMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMetodoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMetodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMetodoLayout.setVerticalGroup(
            pnlMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMetodoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(txtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Analises"));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_plus_24.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_minus_24.png"))); // NOI18N
        btnRemover.setToolTipText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        tblPlanoAnalise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod_Analise_Id", "Descrição", "Análise", "Tipo", "Setor", "Temp Mín", "Temp Médio", "Temp Máx", "Versão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPlanoAnalise.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPlanoAnalise.getTableHeader().setReorderingAllowed(false);
        tblPlanoAnalise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlanoAnaliseMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblPlanoAnalise);
        if (tblPlanoAnalise.getColumnModel().getColumnCount() > 0) {
            tblPlanoAnalise.getColumnModel().getColumn(0).setMinWidth(100);
            tblPlanoAnalise.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblPlanoAnalise.getColumnModel().getColumn(0).setMaxWidth(100);
            tblPlanoAnalise.getColumnModel().getColumn(1).setMinWidth(400);
            tblPlanoAnalise.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblPlanoAnalise.getColumnModel().getColumn(2).setMinWidth(300);
            tblPlanoAnalise.getColumnModel().getColumn(2).setPreferredWidth(300);
            tblPlanoAnalise.getColumnModel().getColumn(3).setMinWidth(300);
            tblPlanoAnalise.getColumnModel().getColumn(3).setPreferredWidth(300);
            tblPlanoAnalise.getColumnModel().getColumn(4).setMinWidth(150);
            tblPlanoAnalise.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblPlanoAnalise.getColumnModel().getColumn(4).setMaxWidth(150);
            tblPlanoAnalise.getColumnModel().getColumn(5).setMinWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(5).setPreferredWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(5).setMaxWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(6).setMinWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(6).setPreferredWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(6).setMaxWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(7).setMinWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(7).setPreferredWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(7).setMaxWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(8).setMinWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(8).setPreferredWidth(80);
            tblPlanoAnalise.getColumnModel().getColumn(8).setMaxWidth(80);
        }

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_edit.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnReagente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_reagente_32.png"))); // NOI18N
        btnReagente.setToolTipText("Vincular Reagente");
        btnReagente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReagenteActionPerformed(evt);
            }
        });

        btnPadrao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_padrao_32.png"))); // NOI18N
        btnPadrao.setToolTipText("Vincular Padrão");
        btnPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadraoActionPerformed(evt);
            }
        });

        btnColuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_coluna.png"))); // NOI18N
        btnColuna.setToolTipText("Vincular Coluna");
        btnColuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColunaActionPerformed(evt);
            }
        });

        btnSolucaoReagente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_solucao_32.png"))); // NOI18N
        btnSolucaoReagente.setToolTipText("Vincular Solução Reagente");
        btnSolucaoReagente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucaoReagenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnReagente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPadrao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnColuna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSolucaoReagente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReagente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSolucaoReagente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMetodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FrmPlanoAnaliseDados frm = new FrmPlanoAnaliseDados(null, true, new Metodologia(metodo_id), true);
        frm.setVisible(true);
        readPlanoAnalise();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (tblPlanoAnalise.getSelectedRow() != -1) {
            remover();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void tblPlanoAnaliseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlanoAnaliseMouseClicked
        if (evt.getClickCount() == 2) {
            if (tblPlanoAnalise.getSelectedRow() != -1) {
                editar();
            }
        }
    }//GEN-LAST:event_tblPlanoAnaliseMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblPlanoAnalise.getSelectedRow() != -1) {
            editar();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnReagenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReagenteActionPerformed
        if (tblPlanoAnalise.getSelectedRow() != -1) {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            FrmPlanoAnaliseReagente frm = new FrmPlanoAnaliseReagente(null, true, metodo_id,
                    (Long) tblPlanoAnalise.getValueAt(tblPlanoAnalise.getSelectedRow(), 0));
            frm.setVisible(true);
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_btnReagenteActionPerformed

    private void btnPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPadraoActionPerformed

    private void btnColunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColunaActionPerformed
        if (tblPlanoAnalise.getSelectedRow() != -1) {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            FrmPlanoAnaliseColuna frm = new FrmPlanoAnaliseColuna(null, true, metodo_id,
                    (Long) tblPlanoAnalise.getValueAt(tblPlanoAnalise.getSelectedRow(), 0));
            frm.setVisible(true);
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_btnColunaActionPerformed

    private void btnSolucaoReagenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucaoReagenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolucaoReagenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPlanoAnaliseConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPlanoAnaliseConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPlanoAnaliseConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPlanoAnaliseConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmPlanoAnaliseConfig dialog = new FrmPlanoAnaliseConfig(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnColuna;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnPadrao;
    private javax.swing.JButton btnReagente;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSolucaoReagente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pnlMetodo;
    private javax.swing.JTable tblPlanoAnalise;
    private javax.swing.JTextField txtMetodo;
    private javax.swing.JTextField txtVersao;
    // End of variables declaration//GEN-END:variables

    private void readPlanoAnalise() {
        DefaultTableModel model = (DefaultTableModel) tblPlanoAnalise.getModel();
        PlanoAnaliseDAO paDAO = new PlanoAnaliseDAO();
        model.setNumRows(0);
        try {
            Metodologia mtd = new MetodologiaDAO().findById(Metodologia.class, metodo_id);
            txtMetodo.setText(mtd.getMetodo().toUpperCase());
            txtVersao.setText(mtd.getVersao().toString());
            for (PlanoAnalise pa : paDAO.readPlanoAnalise(metodo_id)) {
                model.addRow(new Object[]{
                    pa.getId(),
                    pa.getDescricao(),
                    pa.getAnalise().getAnalise(),
                    pa.getAnaliseTipo().getAnaliseTipo(),
                    pa.getSetor().getSiglaSetor(),
                    pa.getLeadTimeMin(),
                    pa.getLeadTimeMedio(),
                    pa.getLeadTimeMax(),
                    pa.getVersion()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
        }
    }

    private void remover() {
        Senha senha = new Senha();
        DefaultTableModel model = (DefaultTableModel) tblPlanoAnalise.getModel();
        PlanoAnaliseDAO mtdAnaliseDAO = new PlanoAnaliseDAO();
        //LoteMateriaPrimaStatusDAO loteStatusDAO = new LoteMateriaPrimaStatusDAO();
        Long pa_id = (Long) tblPlanoAnalise.getValueAt(tblPlanoAnalise.getSelectedRow(), 0);
        try {
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Realmente deseja excluir essa Registro?", "Aviso", JOptionPane.YES_NO_OPTION);
            if (dialogResult == 0) {
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                if (senha.Salvar()) {
                    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//                    for (LoteMateriaPrimaStatus loteStatus : loteStatusDAO.findStatusByPlanoAnalise(pa_id)) {
//                        loteStatusDAO.remover(LoteMateriaPrimaStatus.class, loteStatus.getId());
//                    }
                    mtdAnaliseDAO.remover(PlanoAnalise.class, pa_id);
                    model.removeRow(tblPlanoAnalise.getSelectedRow());
                    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                }
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excuir o dado: " + e.getMessage(), "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
        } finally {
            readPlanoAnalise();
        }
    }

    public void editar() {
        PlanoAnaliseDAO mtdAnaliseDAO = new PlanoAnaliseDAO();
        try {
            PlanoAnalise mtdAnalise = mtdAnaliseDAO.findById(PlanoAnalise.class,
                    (Long) tblPlanoAnalise.getValueAt(tblPlanoAnalise.getSelectedRow(), 0));
            new FrmPlanoAnaliseDados(null, true, mtdAnalise).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e);
        } finally {
            readPlanoAnalise();
        }

    }
}
